### ISSUE TITLE
Better error message when "org.testng.internal.reflect.MethodMatcherException:  Data provider mismatch "

### ISSUE THREAD

**Issue by hemanthsridhar** [testng-team/testng#1031]
**This is what I am sending through my data provider**

``` java
@DataProvider(name="test")
    public static Object[][] test() throws Exception{
        return new Object[][]
                {
            {"","hemanth","sridhar","test123","test123","address1","address2","Topeka","Kansas","66601","1234567890","Super User","","Please enter Email Address."}
            };
    }
```

**This is my signature**

``` java
@Test(groups={"regression"},dataProvider="excelSheetDataRead",dataProviderClass=SearchData.class)
public void TC_PA_008_TC_PA_009_TC_PA_010_TC_PA_011_TC_PA_012_TC_PA_013_TC_PA_014_TC_PA_015_TC_PA_016_TC_A_017_TC_PA_018_TC_PA_019_TC_PA_020_TC_PA_021_TC_PA_022_errorScenarios(String emailId,String firstName, String lastName, String password, String confirmPassword,String address1, String address2, String city, String state, String zipCode,String phoneNumber,String roleAssignment,String faxNumber,String website,String expectedErrorMsg) throws Exception
```

**Complete console log**:

```
org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: TC_PA_008_TC_PA_009_TC_PA_010__TC_PA_011_TC_PA_012_TC_PA_013_TC_PA_014_TC_PA_015_TC_PA_016_TC_A_017_TC_PA_018_TC_PA_019_TC_PA_020_TC_PA_021_TC_PA_022_errorScenarios([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=5, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=6, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=7, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=8, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=9, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=10, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=11, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=12, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=13, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=14, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String),(java.lang.String)hemanth,(java.lang.String)sridhar,(java.lang.String)test123,(java.lang.String)test123,(java.lang.String)address1,(java.lang.String)address2,(java.lang.String)Topeka,(java.lang.String)Kansas,(java.lang.String)66601,(java.lang.String)1234567890,(java.lang.String)Super User,(java.lang.String),(java.lang.String)Please enter Email Address.]
    at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:52)
    at org.testng.internal.Invoker.injectParameters(Invoker.java:1228)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1125)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
    at org.testng.TestRunner.privateRun(TestRunner.java:778)
    at org.testng.TestRunner.run(TestRunner.java:632)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
    at org.testng.SuiteRunner.run(SuiteRunner.java:268)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
    at org.testng.TestNG.runSuites(TestNG.java:1075)
    at org.testng.TestNG.run(TestNG.java:1047)
    at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
```

**Comment by hemanthsridhar** [comment]
This is what I am sending through my data provider
```
@DataProvider(name="test")
	public static Object[][] test() throws Exception{
		return new Object[][]
				{
			{"","hemanth","sridhar","test123","test123","address1","address2","Topeka","Kansas","66601","1234567890","Super User","","Please enter Email Address."}
			};
	}
```
This is my signature
`public void TC_PA_008_TC_PA_009_TC_PA_010_TC_PA_011_TC_PA_012_TC_PA_013_TC_PA_014_TC_PA_015_TC_PA_016_TC_A_017_TC_PA_018_TC_PA_019_TC_PA_020_TC_PA_021_TC_PA_022_errorScenarios(String emailId,String firstName, String lastName, String password, String confirmPassword,String address1, String address2, String city, String state, String zipCode,String phoneNumber,String roleAssignment,String faxNumber,String website,String expectedErrorMsg) throws Exception`

**Comment by himasagar** [comment]
Looks like the test has 15 arguments but from data provider you are passing 14 arguments as input.

**Comment by hemanthsridhar** [comment]
I sincerely apologise for raising an issue with such a silly mistake. Having said that can we have a better error message generated that is more lucid enough to understand?

**Comment by himasagar** [comment]
the error message org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch

Looks fine to me. The data provider mismatches with the data provider expected at test. I don't think changing error message is required.

**Comment by hemanthsridhar** [comment]
If you say so. :) thank you so much. Please close the issue.

**Comment by juherr** [comment]
I think we could be better and be a bit more precise: too much/few parameters. 
But clearly not a priority ;)

**Comment by hemanthsridhar** [comment]
Yeah. Expecting the same :).

**Comment by prakashss056** [comment]
org.testng.internal.reflect.MethodMatcherException: 
**Data provider mismatch**
Method: getregdata([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=5, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=6, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=7, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=8, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=9, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=10, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=11, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=12, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=13, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=14, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=15, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=16, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) prakash,(java.lang.String) s,(java.lang.String) s,(java.lang.String) ab@gmail.com,(java.lang.String) ram,(java.lang.String) 560029,(java.lang.String) India,(java.lang.String) 8197901689,(java.lang.String) 29abcde1234ad78,(java.lang.String) /Users/prakash/Desktop/eclipse-workspace/hybridframework/hybrid/src/main/java/com/hybrid/data/testdata.xlsx,(java.lang.String) infosys,(java.lang.String) mejestic,(java.lang.String) bidar,(java.lang.String) Karnataka,(java.lang.String) 123456,(java.lang.String) 123456,(java.lang.String) y,null,null,null,null,null,null,null,null]
	at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
	at org.testng.internal.Parameters.injectParameters(Parameters.java:796)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:982)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by prakashss056** [comment]
how to resolve this issue

**Comment by juherr** [comment]
@prakashss056 How to reproduce?

**Comment by Kishorekumar2789** [comment]
Am facing the same issue as mentioned by "prakashss056"
org.testng.internal.reflect.MethodMatcherException:
Data provider mismatch

I don't know how to solve this.

**Comment by juherr** [comment]
@Kishorekumar2789 Could you share a full sample that reproduces the issue?

**Comment by Kishorekumar2789** [comment]
> @Kishorekumar2789 Could you share a full sample that reproduces the issue?

@juherr I fix the issue. The error **org.testng.internal.reflect.MethodMatcherException:
Data provider mismatch** occurs due to excel cell format. I just copied the same data and pasted in new excel sheet and execute with same code. It works fine perfectly.

**Work Around**
when reading data from excel, a null get value was added to the Object array. Basically my excel has 7 columns and i have set 7 parameters in Java class to store these 7 data. When this Null added to data object array(now object array has 8 values including Null) and on feeding these data to calling method which 7 parameters it throws error  due to parameter mismatch.

**Comment by SugashiniR** [comment]
I am also facing the same issue, I am using single parameter only in my test and getting single data object at a time from DataProvider, but fails with Method MatcherException, Tried copy  pasting data to different excel still facing same issue. If its excel format issue, is there any other way to fix it.

Below is my code
@DataProvider(name="testdata")
	public Object[][] TestDataEx(){
		ReadExcel ExcelData=new ReadExcel("F:\\SugaProjects\\DataDriven\\src\\test\\resources\\TestData.xlsx");
		int rows=ExcelData.getRowCount("SearchTest");
		System.out.println(rows);
		Object[][] excelobj=new Object[rows][3];
		for(int i=0; i<rows; i++) {
			excelobj[i][0] = ExcelData.getData("SearchTest", i, 0);
		}	
		return excelobj;
	}
	
	@Test(dataProvider="testdata")
	public void secondscript(String searchText) {
		
		driver.findElement(By.xpath("//input[@id='twotabsearchtextbox']")).sendKeys(searchText);
	}

**Comment by krmahadevan** [comment]
Following is what I see in TestNG `7.6.0` (latest released version as of today)

```java
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

public class TestClass {

  @Test(dataProvider = "dp")
  public void testMethod(int a, int b) {
  }

  @DataProvider(name = "dp")
  public Object[][] getData() {
    return new Object[][]{
        {1}
    };
  }
}
```

Error message:

```
org.testng.internal.reflect.MethodMatcherException: 
[public void com.rationaleemotions.issue1031.TestClass.testMethod(int,int)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testMethod([int arg0, int arg1])
Arguments: [(java.lang.Integer) 1]
```

**Comment by juherr** [comment]
Triage verdict: **still relevant**.

The current `DataProviderMethodMatcher` still falls back to a generic `Data provider mismatch` and `MethodMatcherException` then dumps the declared parameters and supplied arguments. That is useful raw data, but it still does not directly say "expected 15 arguments, got 14" (or distinguish count mismatch from an incompatible type), which was the improvement requested here.

Current tests cover matcher failures, so a change should add focused assertions for too few / too many arguments without regressing varargs and injected-parameter cases.

**Comment by kalayciburak** [comment]
I'll work on this.
