### ISSUE TITLE
Count of test in report include Before- and AfterMethod method as separate tests if fail is occurred in such methods.

### ISSUE THREAD

**Issue by pmashurenko** [testng-team/testng#1237]
### TestNG Version
6.9.13.6. Also testsed on 6.8.7 with same result.

### Expected behavior
Count of tests should not depend on results of Before- and AfterMethods status.

### Actual behavior
If Before- or AfterMethod test fail it will cause that count of X tests defined in class will be 
represented in report as approx. 3*X tests.

### Is the issue reproductible on 
- [X] Maven
- [X] Eclipse

### OS
Windows

### Test case sample
    public class BasicRegresComponentsTests extends GenericTest {
    
        public BasicRegresComponentsTests() {
            super();
        }
    
        @BeforeClass
        public void testSetup() {
            new BasicRegresComponentsTests();
        }
    
    
        @Test(dataProvider = "prepareTestData")
        public void TC_COM_PartialCHIDsearch(String browserForTest, TestData testData) {
            //selenium related code here
        };
    
        @Test(dataProvider = "prepareTestData")
        public void
            TC_COM_10002_01_Search_using_Fgrp_set_manually(String browserForTest, TestData testData) {
            //selenium related code here
        };
    
        @Test(dataProvider = "prepareTestData")
        public void TC_COM_10002_02_Search_using_Fgrp_choose_from_an_image(String browserForTest, TestData testData) {
            //selenium related code here
        };
    
        @Test(dataProvider = "prepareTestData")
        public void TC_COM_10002_03_Search_using_Fgrp_choose_from_a_tree(String browserForTest, TestData testData) {
            //selenium related code here
        };
    	
        //next 16 tests here Total count of tests in class 19. Expected count of tests in report is 20 as 
        //TC_COM_PartialCHIDsearch should be executed twice due to testData.
    }
    

    public abstract class GenericTest {
    
        public GenericTest() {
            //constructor here
        }
    
        @BeforeMethod
        public void initTest(Method testContext, Object[] testArgs) {
    	//test setup code here
            throw new TestException("TestSetup execption simulation");
        }
    
        @AfterMethod
        public void finishTest() {
            //test teardown code here
    	//throw new TestException("TestTeardown execption simulation");
        }
    
        @DataProvider(name = "prepareTestData")
        public Object[][] getSpecificTestCaseData(Method testContext) {
            //fetching data for specific test
        }
    	
        //some additional methods here
    }

### Failed run in Maven 
    mvn clean test  -Dmaven.test.failure.ignore=true -Dmaven.clean.failOnError=false -Dimpact.mode=online -DrunSuite=test.xml -Dspecified.browsers=chrome
    ...
    [INFO] Surefire report directory: C:\work\WebClientTestTestNG\target\surefire-reports
    
    -------------------------------------------------------
     T E S T S
    -------------------------------------------------------
    Running TestSuite
    [2016-11-15 12:11:05,259]INFO      0[main] - custom.test.setup.TestProperties.build(TestProperties.java:66) - Test artifacts from current run will be saved to: C:\work\WebClientTestTestNG/results/2016-11-15_12.11.05
    [2016-11-15 12:11:05,262]INFO      3[main] - custom.test.setup.TestProperties.build(TestProperties.java:74) - Test properties for the test run were successfully loaded from file
    [2016-11-15 12:11:05,262]INFO      3[main] - custom.test.setup.TestProperties.build(TestProperties.java:93) - Database will not be cleared. It has been blocked manually
    Tests run: 60, Failures: 1, Errors: 0, Skipped: 59, Time elapsed: 1.067 sec <<< FAILURE! - in TestSuite
    initTest(custom.test.testcases.BasicRegresComponentsTests)  Time elapsed: 0.751 sec  <<< FAILURE!
    org.testng.TestException:
    TestSetup execption simulation
            at custom.test.setup.GenericTest.initTest(GenericTest.java:59)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            ...
            at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
            at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
            at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
            at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
    
    Picked up JAVA_TOOL_OPTIONS: -agentlib:jvmhook
    Picked up _JAVA_OPTIONS: -Xrunjvmhook -Xbootclasspath/a:"C:\Program Files (x86)\HP\Sprinter\bin\java_shared\classes";"C:\Program Files (x86)\HP\Sprinter\\bin\java_shared\classes\jasmine.jar"
    
    Results :
    
    Failed tests:
      BasicRegresComponentsTests>GenericTest.initTest:59 ▒ Test
    TestSetup exec...
    
    Tests run: 60, Failures: 1, Errors: 0, Skipped: 59
    
    [ERROR] There are test failures.
    
    Please refer to C:\work\WebClientTestTestNG\target\surefire-reports for the individual test results.

### Passed run in Maven
    mvn clean test  -Dmaven.test.failure.ignore=true -Dmaven.clean.failOnError=false -Dimpact.mode=online -DrunSuite=test.xml -Dspecified.browsers=chrome
    ...
    Tests run: 20, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 327.159 sec - in TestSuite
    Picked up JAVA_TOOL_OPTIONS: -agentlib:jvmhook
    Picked up _JAVA_OPTIONS: -Xrunjvmhook -Xbootclasspath/a:"C:\Program Files (x86)\HP\Sprinter\bin\java_shared\classes";"C:\Program Files (x86)\HP\Sprinter\\bin\java_shared\classes\jasmine.jar"
    
    Results :
    
    Tests run: 20, Failures: 0, Errors: 0, Skipped: 0

### Failed run in Eclipse
![eclipse_fail](https://cloud.githubusercontent.com/assets/1726482/20308621/11faa232-ab45-11e6-99e9-1374fd6fbb5e.jpg)

### Passed run in Eclipse
![eclipse_pass](https://cloud.githubusercontent.com/assets/1726482/20308624/18ea2338-ab45-11e6-886e-0a9c1e1a21f3.jpg)

**Comment by juherr** [comment]
I don't have the historical reason, but I think it is the expected behavior. Ping @cbeust

**Comment by cbeust** [comment]
Honestly, I can't tell if it's intentional or just a consequence of how
it's implemented.

-- 
Cédric

**Comment by juherr** [comment]
In fact, as I remember, the current model doesn't have a direct link between test methods and configuration methods. So I think it is the only one way to understand why tests are skipped.

@missedone Any idea/remarks?

**Comment by gavrilfb** [comment]
Hi, so I was having this exact issue.
Just want to know if there's any update on this.

I use Jenkins and TestNG and use the console logs for reporting to TelegramBot.
This is what I get currently if i intentionally failed the `@BeforeTest` for all xml suites.
<img width="897" alt="image" src="https://user-images.githubusercontent.com/29943195/46861568-1b3b5400-ce3d-11e8-8b90-6eeae645c3f8.png">

It would be great if the numbers displayed is just the skipped `@Test` instead of all the methods skipped because of the failed `@BeforeTest`

After some searching, I found this piece of code, but no luck.
`public void onFinish(ITestContext iTestContext) {
		Set<ITestResult> skippedTests = iTestContext.getSkippedTests().getAllResults();
		for (ITestResult temp : skippedTests) {
			ITestNGMethod method = temp.getMethod();
			if (!method.isTest()) {
				skippedTests.remove(temp);
				continue;
			}
			if (iTestContext.getSkippedTests().getResults(method).size() > 1) {
				skippedTests.remove(temp);
			} else {
				if (iTestContext.getPassedTests().getResults(method).size() > 0) {
					skippedTests.remove(temp);
				} else {
					if (iTestContext.getFailedTests().getResults(method).size() > 0) {
						skippedTests.remove(temp);
					}
				}
			}
		}
	}`
But still counting those non-test methods as skipped.

**Comment by krmahadevan** [comment]
@gavrilfb - What version are you using? Please check if this issue is reproducible using the latest released version of TestNG (7.0.0-beta1)

**Comment by gavrilfb** [comment]
Same results, using 6.14.2 or 7.0.0-beta1. @krmahadevan

**Comment by AtMohs** [comment]
still facing this issue, can some one please help ? thanks in advance

**Comment by kylejessetaylor** [comment]
I am also having this exact issue, specifically when skipping tests with a SkipException in a @beforeMethod.

I'll run my suite, in my IDE it shows my total test skipped as [1 (expected)](https://imgur.com/YJ6DHCh), but sometimes when using other tools such as Jenkins it [triples the value (3)](https://imgur.com/UebINiX). Any advice?

**Comment by smilinrobin** [comment]
Facing a similar issue, where the count of executed tests includes BeforeTest/AfterTest methods as well and thereby spoiling the number of tests reported into XRAY/JIRA, when the results are imported via testng-results.xml.

**Comment by pavitrajainqt** [comment]
facing same issue in the latest version of testng i.e. 7.1.0
Is there a work around?

**Comment by mlaurie** [comment]
For anyone else looking, the unexpected count is coming from maven surefire plugin, not testNg.
TestNg uses the surefire report mechanism by default, so this shows up in testng output.
Options for you:
1) hide output from surefire: `[-Dsurefire.printSummary=false](https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#printSummary )` (with some caveats) 
2) Provide your own custom reporter using something like [testng.IReporter](https://testng.org/doc/documentation-main.html#logging-reporters)

**Comment by Proryanator** [comment]
@mlaurie any thoughts on how you could make a custom IReporter that only counts the @Test methods? :D might be a good workaround for those of us still having the same problem.

We're on version 7.3.0 and we see this when config methods fail. Granted, should not fail but, sometimes they do.

**Comment by juherr** [comment]
AI triage verdict: **working as designed**.

Current TestNG keeps test and configuration results separate. Its native summary counts passed/failed/skipped/retried **test** results and reports configuration failures/skips separately. `VerboseReporter` likewise reads `getSkippedTests()` separately from `getFailedConfigurations()` / `getSkippedConfigurations()`. `testng-results.xml` intentionally contains configuration invocations as `<test-method>` entries, but marks them with `is-config="true"`; consumers are expected to distinguish them. This is necessary to retain configuration failure details.

The inflated Maven summary shown in the issue was also identified in the discussion as Surefire's counting/reporting convention, not TestNG's native test count. Other consumers importing `testng-results.xml` need to honor `is-config`. I found no `GITHUB-1237` change or open/merged PR proposing to remove configuration invocations from TestNG result reporting.

The historical reproducer was **not executed** in this triage pass. Current code directly establishes the result separation and XML contract.

No TestNG production change is required. A consumer that needs a count of `@Test` invocations should use the test result maps or ignore XML entries with `is-config="true"`; runner-specific summaries should be addressed in that runner.
