### ISSUE TITLE
Null fields in parallel method tests

### ISSUE THREAD

**Issue by ben-manes** [testng-team/testng#1625]
This occurs in 6.13 and was working in 6.12.

```java
public final class BeforeClassTest {
  @Mock List<String> list;

  @BeforeClass
  public void beforeClass() {
    MockitoAnnotations.initMocks(this);
  }

  @Test
  public void first() {
    Assert.assertNotNull(list);
  }

  @Test
  public void second() {
    Assert.assertNotNull(list);
  }
}
```

The `first` test passes and the `second` test fails with an NPE.
```
java.lang.AssertionError: expected object to not be null
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.assertNotNull(Assert.java:686)
	at org.testng.Assert.assertNotNull(Assert.java:671)
```

If `@Test(singleThreaded = true)` is added to the class, then both tests succeed.

Strangely, when I replace the mock initialization with `list = new ArrayList<>();` then they both pass. I suspect there's some trigger in whether the methods were parallelized or not.

This occurs in my project and can be reproduced there as,
```
$ gradle strongKeysAndStrongValuesStatsSyncCaffeineTest \
    -DstrongKeysAndStrongValuesStatsSyncCaffeineTest.single=CaffeineTest
```
after upgrading the version in `dependency.gradle`

**Comment by krmahadevan** [comment]
@ben-manes - I tried running this on the `master` branch of the TestNG codebase itself (since I guess 6.13 is not officially released yet and whatever was published got removed as well maybe). I cannot reproduce the problem.

Added the below to the gradle build file 

```
testCompile group: 'org.mockito', name: 'mockito-core', version: '2.12.0'
```

I ran the below class

```java
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.testng.Assert;
import org.testng.TestNG;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import java.util.List;

public class Issue1625TestSample {
    @Mock
    List<String> list;

    @BeforeClass
    public void beforeClass() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void first() {
        Assert.assertNotNull(list);
    }

    @Test
    public void second() {
        Assert.assertNotNull(list);
    }

    public static void main(String[] args) {
        TestNG testNG = new TestNG();
        testNG.setTestClasses(new Class[]{Issue1625TestSample.class});
        testNG.setVerbose(3);
        testNG.run();
    }
}
```

Output is as below

```
===== Invoked methods
  Issue1625TestSample.beforeClass()[pri:0, instance:rationale.emotions.Issue1625TestSample@70177ecd] 1880587981
    Issue1625TestSample.first()[pri:0, instance:rationale.emotions.Issue1625TestSample@70177ecd] 1880587981
    Issue1625TestSample.second()[pri:0, instance:rationale.emotions.Issue1625TestSample@70177ecd] 1880587981
=====
PASSED: first
PASSED: second

===============================================
    Command line test
    Tests run: 2, Failures: 0, Skips: 0
===============================================


===============================================
Command line suite
Total tests run: 2, Failures: 0, Skips: 0
===============================================


Process finished with exit code 0
```

**Comment by ben-manes** [comment]
Did you enable parallel methods? When I’d run in Eclipse it works, but in my Gradle build it failed.

**Comment by krmahadevan** [comment]
Aha! Yes, I now see the issue.

The main method should have been 

```java
    public static void main(String[] args) {
        TestNG testNG = new TestNG();
        testNG.setTestClasses(new Class[]{Issue1625TestSample.class});
        testNG.setParallel(XmlSuite.ParallelMode.METHODS);
        testNG.setVerbose(3);
        testNG.run();
    }
```

The output now is 
```
===== Invoked methods
  Issue1625TestSample.beforeClass()[pri:0, instance:rationale.emotions.Issue1625TestSample@70177ecd] 1880587981
    Issue1625TestSample.second()[pri:0, instance:rationale.emotions.Issue1625TestSample@70177ecd] 1880587981
    Issue1625TestSample.first()[pri:0, instance:rationale.emotions.Issue1625TestSample@70177ecd] 1880587981
=====
PASSED: first
FAILED: second
java.lang.AssertionError: expected object to not be null
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.assertNotNull(Assert.java:686)
	at org.testng.Assert.assertNotNull(Assert.java:671)
	at rationale.emotions.Issue1625TestSample.second(Issue1625TestSample.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by ben-manes** [comment]
Thanks for the quick turnaround! :)

**Comment by krmahadevan** [comment]
@ben-manes - No problem. It was more of a guilt feel, coz it was my change earlier that broke the functionality :(

**Comment by ben-manes** [comment]
Don't. :) It is kind of an unexpected usage, as mutable shared variables wouldn't be safe in most parallel method tests. I just needed some configuration instances for assertions on the builder and the mocks were the least amount of code to do so, as they are untouched otherwise. All the other tests use data providers so it was a rare stumble.
