### ISSUE TITLE
TestNG is no longer working in OSGi environments

### ISSUE THREAD

**Issue by adessaigne** [testng-team/testng#1678]
### TestNG Version
TestNG 6.13.1

### Expected behavior
TestNG is working in OSGi environments

### Actual behavior
When starting TestNG in a OSGi environment you have the following exception
```
java.lang.ClassNotFoundException: com.beust.jcommander.ParameterException not found by testng [72]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1550)
	at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1958)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
```

The reason behind that is that the `MANIFEST.MF` file no longer contain the `Import-Package` directive.

Unfortunately I don't know how to fix it, can you have a look ? Thanks.

**Comment by missedone** [comment]
Probably you can try this before it fixed in testng core: https://github.com/testng-team/testng-p2

**Comment by juherr** [comment]
It should be fixed in the next release. Could you try 6.14.0-RC2 from JCenter and confirm it?

**Comment by adessaigne** [comment]
Hello,

I've tested few versions:
* 6.14.0-RC2 from JCenter has the OSGi `Import-Package` but doesn't work because TestNG has a compile dependency towards Guice which has a dependency towards javax.inject which misses the OSGi metadata
* 6.14.0-RC4 from JCenter doesn't work because it doesn't have the OSGi `Import-Package` and the OSGi version is 6.14.0-RC4 and not 6.14.0.RC4 (use a dash instead of a dot)
* 6.14.2 from Maven central doesn't have the OSGi `Import-Package`

And regarding TestNG-P2, do you have docs on how to reference it in a maven project ? Thanks.

**Comment by missedone** [comment]
the testng-p2 is only available as [P2 repo](https://dl.bintray.com/testng-team/testng-p2/updatesites/6.14.2.b201802050707/) (aka, eclipse update site) for OSGi env.
to test with maven, as a workaround, you can download the jars and manually install to your local maven repo.

1. osgified testng jar: https://dl.bintray.com/testng-team/testng-p2/updatesites/6.14.2.b201802050707/plugins/
2. maven install file to local repo: https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html

**Comment by krmahadevan** [comment]
@missedone - Please advice if this issue can be closed

**Comment by missedone** [comment]
@krmahadevan, i think we need keep it open till have a proper fix in the OSGI headers

**Comment by laeubi** [comment]
Is there any chance this can be addressed? Currently the manifest is completely broken:

- https://github.com/testng-team/testng/issues/1190#issuecomment-2692241277

**Comment by krmahadevan** [comment]
This should have gotten fixed via https://github.com/testng-team/testng/pull/3213

**Comment by laeubi** [comment]
Thanks! Please let me know once there is a new release at central!
