### ISSUE TITLE
OutOfMemoryError: Java heap space exception after upgrading TestNG to 6.14.3

### ISSUE THREAD

**Issue by dvelinovska** [testng-team/testng#1907]
### TestNG Version
**6.14.3**

**Description:**

After upgrading to latest version of TestNg I'm trying to run regression suite containing ~1700 tests. After 471 executed test I get OutOfMemoryError: Java heap space exception. If I switch back to the previous version I've used (6.9.5) all tests are executed without a problem
I tried disabling default listeners by adding in my .pom but problem still exists. 
```xml
         <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <properties>
                        <property>
                            <name>usedefaultlisteners</name>
                            <key>false</key>
                        </property>
                    </properties>
                </configuration>
            </plugin>
```

### Expected behavior
Test successfully executed 

### Actual behavior
```
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:261)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
	at java.util.ArrayList.add(ArrayList.java:458)
	at org.testng.collections.MultiMap.put(MultiMap.java:31)
	at org.testng.internal.DynamicGraph.addEdges(DynamicGraph.java:103)
	at org.testng.internal.DynamicGraph.addEdge(DynamicGraph.java:72)
	at org.testng.internal.DynamicGraph.setStatus(DynamicGraph.java:250)
	at org.testng.internal.DynamicGraph.setStatus(DynamicGraph.java:208)
	at org.testng.TestRunner.privateRun(TestRunner.java:650)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
```

### Is the issue reproductible on runner?
- [x] Maven
- [x] IntelliJ

**Comment by krmahadevan** [comment]
@dvelinovska - Can you please quickly check if using TestNG `7.0.0-SNAPSHOT` fixes the problem or still causes the same problem and let us know the outcome ?

**Comment by dvelinovska** [comment]
@krmahadevan I'm not able to resolve dependency for the mentioned version
 Dependency 'org.testng:testng:7.0.0-SNAPSHOT' not found

**Comment by krmahadevan** [comment]
@dvelinovska - You then perhaps need to add a `<repository>` tag entry as explained [here](https://www.mkyong.com/maven/how-to-add-remote-repository-in-maven-pom-xml/) for [OSS Snapshots](https://oss.sonatype.org/content/repositories/snapshots/org/testng/testng/) and then try again.

**Comment by juherr** [comment]
@dvelinovska 7.0.0-beta1 is now available on maven central: https://search.maven.org/artifact/org.testng/testng/7.0.0-beta1/jar
Could you check again with this version?

**Comment by krmahadevan** [comment]
ping @dvelinovska - Did you get a chance to revisit this issue ?

**Comment by dvelinovska** [comment]
> ping @dvelinovska - Did you get a chance to revisit this issue ?

I tried with beta version but I still get strange behavior ... it seems like that after running number of test ~550 I starts hanging on before method and after method execution  and tests cease with execution
There is no error  thrown.
![testng](https://user-images.githubusercontent.com/16703809/49210226-d8b5e280-f3bc-11e8-9768-a3f0a108c5e1.PNG)
![testng2](https://user-images.githubusercontent.com/16703809/49210227-d94e7900-f3bc-11e8-9b96-2a27344c3dd3.PNG)

**Comment by krmahadevan** [comment]
@dvelinovska would it be possible for you to please help share a sample project that we can use to reproduce the problem ?

**Comment by krmahadevan** [comment]
No answer from user. Closing this issue.
