### ISSUE TITLE
Running testng-failed.xml correctly runs failed test in child class but incorrectly runs all tests in base class

### ISSUE THREAD

**Issue by ravinishant** [testng-team/testng#1930]
**TestNG version - 6.14.3
IDE - IntelliJ**

# Explanation -

I have tests distributed across child class and a base class that it extends from. Both the classes are in different packages.

**DataProviderTest.class**

```java
package com.rambo.rambokart;

import org.testng.Assert;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

import com.rambo.zamboKart.TestBase;

public class DataProviderTest extends TestBase {

	private PrimeNumberChecker primeNumberChecker;

	@BeforeMethod
	public void initialize() {
		primeNumberChecker = new PrimeNumberChecker();
	}

	@DataProvider(name = "test1")
	public static Object[][] primeNumbers() {
		return new Object[][] {{2, true}, {6, false}, {19, true}, {22, true}, {23, false}};
	}

	@Test(dataProvider = "test1")
	public void testPrimeNumberChecker(Integer inputNumber, Boolean expectedResult) {
		System.out.println(inputNumber + " " + expectedResult);
		Assert.assertEquals(expectedResult, primeNumberChecker.validate(inputNumber));
	}
}
```

**TestBase.class**

```java
package com.rambo.zamboKart;

import org.testng.Assert;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

public class TestBase {

	@Test(dataProvider = "test2")
	public void testNumberEquality(Integer i1, Integer i2) {
		Assert.assertEquals(i1,i2);
	}

	@DataProvider(name = "test2")
	public static Object[][] numbers() {
		return new Object[][] {{2, 2}, {6, 6}, {19, 18}, {22, 21}, {23, 23}};
	}
}
```

# Suite File - MyTestNG.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="Main Test Suite" verbose="2">

    <test name="DataProvider Tests">
        <classes>
            <class name="com.rambo.rambokart.DataProviderTest" />
        </classes>
    </test>
</suite>
```

Running the above suite file, will run all the tests from DataProviderTest and TestBase class as shown below - 

![image](https://user-images.githubusercontent.com/16848396/46689863-ad312b80-cbb5-11e8-8e61-8997a5e9a726.png)

Now we have following testNG-failed.xml created - 

# testNG-failed.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Main Test Suite]">

  <test thread-count="5" verbose="2" name="DataProvider Tests(failed)">
    <classes>
      <class name="com.rambo.rambokart.DataProviderTest">
        <methods>
          <include name="testNumberEquality" invocation-numbers="2 3"/>
          <include name="initialize"/>
          <include name="testPrimeNumberChecker" invocation-numbers="3 4"/>
        </methods>
      </class>
    </classes>
  </test>
</suite>
```

Running this testNG-failed xml gives following output - 

![image](https://user-images.githubusercontent.com/16848396/46689952-ed90a980-cbb5-11e8-8252-bb9a5b17adb1.png)

**Actual** - This test run also runs tests from TestBase class that were successful in their initial run. Note that only failed tests from DataProviderTest class is being executed. SO, behavior is correct for child class but not for class being extended.

**Expected** - Only failed test from classes DataProviderTest and TestBase should run.

**Comment by krmahadevan** [comment]
@ravinishant - What happens when you try using TestNG [7.0.0-beta1](http://repo1.maven.org/maven2/org/testng/testng/7.0.0-beta1/) ? Can you please try again and post back the results ?

**Comment by ravinishant** [comment]
@krmahadevan I tried with TestNG 7.0.0-beta1 and found **same result**. I also verified that testNG-failed.xml file that was generated had exactly same content.

**Comment by juherr** [comment]
@ravinishant Could you try a run with the TestNG command line? It will exclude the overhead from IDE.

**Comment by ravinishant** [comment]
@juherr @krmahadevan 

As suggested, I tried running my suite file - testng.xml with TestNG command line. Then I executed TestNG-failed.xml with TestNG command line.

I saw following behavior (which is same as running with IntelliJ IDE)

**TestNG.xml**

```
nishant-macOS:resources nishant$ java -classpath "/Users/nishant/mylib/jcommander-1.72.jar:/Users/nishant/mylib/rambo-kart-0.0.1-SNAPSHOT.jar:/Users/nishant/mylib/testng-7.0.0-beta1.jar:/Users/nishant/mylib/rambo-kart-0.0.1-SNAPSHOT-tests.jar:." org.testng.TestNG testNG.xml 
...
... TestNG 7.0.0-beta1 by Cédric Beust (cedric@beust.com)
...

2 true
6 false
19 true
22 true
23 false
PASSED: testPrimeNumberChecker(2, true)
PASSED: testPrimeNumberChecker(6, false)
PASSED: testPrimeNumberChecker(19, true)
PASSED: testNumberEquality(2, 2)
PASSED: testNumberEquality(6, 6)
PASSED: testNumberEquality(23, 23)
FAILED: testPrimeNumberChecker(22, true)
java.lang.AssertionError: did not expect to find [false] but found [true]
        at org.testng.Assert.fail(Assert.java:97)
        at org.testng.Assert.failNotEquals(Assert.java:969)
        at org.testng.Assert.assertEqualsImpl(Assert.java:136)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:563)
        at com.rambo.rambokart.DataProviderTest.testPrimeNumberChecker(DataProviderTest.java:44)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:658)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:792)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1103)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
        at org.testng.TestRunner.privateRun(TestRunner.java:739)
        at org.testng.TestRunner.run(TestRunner.java:589)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
        at org.testng.SuiteRunner.run(SuiteRunner.java:302)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1145)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
        at org.testng.TestNG.runSuites(TestNG.java:997)
        at org.testng.TestNG.run(TestNG.java:965)
        at org.testng.TestNG.privateMain(TestNG.java:1291)
        at org.testng.TestNG.main(TestNG.java:1259)

FAILED: testPrimeNumberChecker(23, false)
java.lang.AssertionError: did not expect to find [true] but found [false]
        at org.testng.Assert.fail(Assert.java:97)
        at org.testng.Assert.failNotEquals(Assert.java:969)
        at org.testng.Assert.assertEqualsImpl(Assert.java:136)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:563)
        at com.rambo.rambokart.DataProviderTest.testPrimeNumberChecker(DataProviderTest.java:44)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:658)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:792)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1103)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
        at org.testng.TestRunner.privateRun(TestRunner.java:739)
        at org.testng.TestRunner.run(TestRunner.java:589)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
        at org.testng.SuiteRunner.run(SuiteRunner.java:302)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1145)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
        at org.testng.TestNG.runSuites(TestNG.java:997)
        at org.testng.TestNG.run(TestNG.java:965)
        at org.testng.TestNG.privateMain(TestNG.java:1291)
        at org.testng.TestNG.main(TestNG.java:1259)

FAILED: testNumberEquality(19, 18)
java.lang.AssertionError: did not expect to find [18] but found [19]
        at org.testng.Assert.fail(Assert.java:97)
        at org.testng.Assert.failNotEquals(Assert.java:969)
        at org.testng.Assert.assertEqualsImpl(Assert.java:136)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:563)
        at com.rambo.zamboKart.TestBase.testNumberEquality(TestBase.java:29)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:658)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:792)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1103)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
        at org.testng.TestRunner.privateRun(TestRunner.java:739)
        at org.testng.TestRunner.run(TestRunner.java:589)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
        at org.testng.SuiteRunner.run(SuiteRunner.java:302)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1145)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
        at org.testng.TestNG.runSuites(TestNG.java:997)
        at org.testng.TestNG.run(TestNG.java:965)
        at org.testng.TestNG.privateMain(TestNG.java:1291)
        at org.testng.TestNG.main(TestNG.java:1259)

FAILED: testNumberEquality(22, 21)
java.lang.AssertionError: did not expect to find [21] but found [22]
        at org.testng.Assert.fail(Assert.java:97)
        at org.testng.Assert.failNotEquals(Assert.java:969)
        at org.testng.Assert.assertEqualsImpl(Assert.java:136)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:563)
        at com.rambo.zamboKart.TestBase.testNumberEquality(TestBase.java:29)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:658)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:792)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1103)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
        at org.testng.TestRunner.privateRun(TestRunner.java:739)
        at org.testng.TestRunner.run(TestRunner.java:589)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
        at org.testng.SuiteRunner.run(SuiteRunner.java:302)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1145)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
        at org.testng.TestNG.runSuites(TestNG.java:997)
        at org.testng.TestNG.run(TestNG.java:965)
        at org.testng.TestNG.privateMain(TestNG.java:1291)
        at org.testng.TestNG.main(TestNG.java:1259)


===============================================
    DataProvider Tests
    Tests run: 10, Failures: 4, Skips: 0
===============================================


===============================================
Main Test Suite
Total tests run: 10, Passes: 6, Failures: 4, Skips: 0
===============================================
```

**TestNG-failed.xml file generated**

```XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite guice-stage="DEVELOPMENT" verbose="2" name="Failed suite [Main Test Suite]">
  <test thread-count="5" verbose="2" name="DataProvider Tests(failed)">
    <classes>
      <class name="com.rambo.rambokart.DataProviderTest">
        <methods>
          <include name="testNumberEquality" invocation-numbers="2 3"/>
          <include name="initialize"/>
          <include name="testPrimeNumberChecker" invocation-numbers="3 4"/>
        </methods>
      </class>
    </classes>
  </test>
</suite> 
```

**TestNG-failed.xml file execution**

```
nishant-macOS:target nishant$ java -classpath "/Users/nishant/mylib/jcommander-1.72.jar:/Users/nishant/mylib/rambo-kart-0.0.1-SNAPSHOT.jar:/Users/nishant/mylib/testng-7.0.0-beta1.jar:/Users/nishant/mylib/rambo-kart-0.0.1-SNAPSHOT-tests.jar:." org.testng.TestNG testng-failed.xml 
...
... TestNG 7.0.0-beta1 by Cédric Beust (cedric@beust.com)
...

22 true
23 false
PASSED: testNumberEquality(2, 2)
PASSED: testNumberEquality(6, 6)
PASSED: testNumberEquality(23, 23)
FAILED: testNumberEquality(19, 18)
java.lang.AssertionError: did not expect to find [18] but found [19]
        at org.testng.Assert.fail(Assert.java:97)
        at org.testng.Assert.failNotEquals(Assert.java:969)
        at org.testng.Assert.assertEqualsImpl(Assert.java:136)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:563)
        at com.rambo.zamboKart.TestBase.testNumberEquality(TestBase.java:29)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:658)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:792)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1103)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
        at org.testng.TestRunner.privateRun(TestRunner.java:739)
        at org.testng.TestRunner.run(TestRunner.java:589)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
        at org.testng.SuiteRunner.run(SuiteRunner.java:302)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1145)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
        at org.testng.TestNG.runSuites(TestNG.java:997)
        at org.testng.TestNG.run(TestNG.java:965)
        at org.testng.TestNG.privateMain(TestNG.java:1291)
        at org.testng.TestNG.main(TestNG.java:1259)

FAILED: testNumberEquality(22, 21)
java.lang.AssertionError: did not expect to find [21] but found [22]
        at org.testng.Assert.fail(Assert.java:97)
        at org.testng.Assert.failNotEquals(Assert.java:969)
        at org.testng.Assert.assertEqualsImpl(Assert.java:136)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:563)
        at com.rambo.zamboKart.TestBase.testNumberEquality(TestBase.java:29)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:658)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:792)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1103)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
        at org.testng.TestRunner.privateRun(TestRunner.java:739)
        at org.testng.TestRunner.run(TestRunner.java:589)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
        at org.testng.SuiteRunner.run(SuiteRunner.java:302)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1145)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
        at org.testng.TestNG.runSuites(TestNG.java:997)
        at org.testng.TestNG.run(TestNG.java:965)
        at org.testng.TestNG.privateMain(TestNG.java:1291)
        at org.testng.TestNG.main(TestNG.java:1259)

FAILED: testPrimeNumberChecker(22, true)
java.lang.AssertionError: did not expect to find [false] but found [true]
        at org.testng.Assert.fail(Assert.java:97)
        at org.testng.Assert.failNotEquals(Assert.java:969)
        at org.testng.Assert.assertEqualsImpl(Assert.java:136)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:563)
        at com.rambo.rambokart.DataProviderTest.testPrimeNumberChecker(DataProviderTest.java:44)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:658)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:792)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1103)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
        at org.testng.TestRunner.privateRun(TestRunner.java:739)
        at org.testng.TestRunner.run(TestRunner.java:589)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
        at org.testng.SuiteRunner.run(SuiteRunner.java:302)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1145)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
        at org.testng.TestNG.runSuites(TestNG.java:997)
        at org.testng.TestNG.run(TestNG.java:965)
        at org.testng.TestNG.privateMain(TestNG.java:1291)
        at org.testng.TestNG.main(TestNG.java:1259)

FAILED: testPrimeNumberChecker(23, false)
java.lang.AssertionError: did not expect to find [true] but found [false]
        at org.testng.Assert.fail(Assert.java:97)
        at org.testng.Assert.failNotEquals(Assert.java:969)
        at org.testng.Assert.assertEqualsImpl(Assert.java:136)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:563)
        at com.rambo.rambokart.DataProviderTest.testPrimeNumberChecker(DataProviderTest.java:44)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:658)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:792)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1103)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
        at org.testng.TestRunner.privateRun(TestRunner.java:739)
        at org.testng.TestRunner.run(TestRunner.java:589)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
        at org.testng.SuiteRunner.run(SuiteRunner.java:302)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1145)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
        at org.testng.TestNG.runSuites(TestNG.java:997)
        at org.testng.TestNG.run(TestNG.java:965)
        at org.testng.TestNG.privateMain(TestNG.java:1291)
        at org.testng.TestNG.main(TestNG.java:1259)


===============================================
    DataProvider Tests(failed)
    Tests run: 7, Failures: 4, Skips: 0
===============================================


===============================================
Failed suite [Main Test Suite]
Total tests run: 7, Passes: 3, Failures: 4, Skips: 0
===============================================

```

**Expected** - Only 4 failed test from previous run, that are included in testNG-failed.xml should run (and fail again). However, few already "PASSED" test from previous run are also executed.

**Comment by ravinishant** [comment]
@juherr @krmahadevan  The problem seems to be here - 
Class- XmlTest.java

```java
public List<Integer> getInvocationNumbers(String method) {
    if (m_failedInvocationNumbers == null) {
      m_failedInvocationNumbers = Maps.newHashMap();
      for (XmlClass c : getXmlClasses()) {
        for (XmlInclude xi : c.getIncludedMethods()) {
          List<Integer> invocationNumbers = xi.getInvocationNumbers();
          if (invocationNumbers.size() > 0) {
            String methodName = c.getName() + "." + xi.getName();
            m_failedInvocationNumbers.put(methodName, invocationNumbers);
          }
        }
      }
    }

    List<Integer> result = m_failedInvocationNumbers.get(method);
    if (result == null) {
      // Don't use emptyList here since this list might end up receiving values if
      // the test run fails.
      return Lists.newArrayList();
    } else {
      return result;
    }
  }
}
```

The Issue - 
The method parameter has value - com.rambo.zamboKart.**TestBase**.testNumberEquality
However, the map "m_failedInvocationNumbers"has no entry for the above fully qualified method.
instead it has entry for "com.rambo.rambokart.**DataProviderTest**.testNumberEquality"

So, It seems that the invocation numbers are stored corresponding to method testNumberEquality referenced by its containing class - **DataProviderTest**

However, while fetching invocation numbers the method testNumberEquality is referenced by its base class - **TestBase**

**Comment by krmahadevan** [comment]
@ravinishant - Since you have done so much analysis, why not raise a PR with the changes? We can help you get it merged.

**Comment by ravinishant** [comment]
@krmahadevan  Thanks. I will be working on this now and raise a PR.

**Comment by chethanvmware** [comment]
Hi, 
I have got a fix for this issue, is it okay to raise a PR?

**Comment by juherr** [comment]
@chethanvmware Feel free to propose your fix if you have one :)

**Comment by krmahadevan** [comment]
@chethanvmware - In case you need help in figuring out how to contribute, please refer [here](https://github.com/cbeust/testng/blob/master/CONTRIBUTING.md)

**Comment by krmahadevan** [comment]
@ravinishant @chethanvmware - ping! Any updates on this PR ?
