### ISSUE TITLE
Same thread names when time outed thread keeps running

### ISSUE THREAD

**Issue by rikiel** [testng-team/testng#2091]
### TestNG Version
> 7.0.0-beta4

### Expected behavior
After time out in test occurs, testng sends interruption signal to runner thread. Thread is free to ignore that signal and can keep running.
When signal is delivered, testng starts new thread for same test and use next item from data provider. In that time, there are 2 threads running parallel and both of them have the same name.
In  `MethodInvocationHelper#invokeWithTimeoutWithNewExecutor()` one can see that every test invoke creates new executor and that executor has numbering for threads again starting at 1.

Better behaviour would be to share same executor, or somehow name all threads by different thread number.

### Is the issue reproductible on runner?

- [x] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
```
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

public class ThreadNameTest {
    @Test(timeOut = 300, dataProvider = "testDataProvider")
    public void test(int i) {
        boolean interrupted = false;
        while (true) {
            try {
                Thread.sleep(100);
                System.out.println(String.format("test-%s: Name = %s; interrupted = %s", i, Thread.currentThread().getName(), interrupted));
            } catch (InterruptedException e) {
                interrupted = true;
            }
        }
    }

    @DataProvider
    public Object[][] testDataProvider() {
        return new Object[][] {
                {1},
                {2}
        };
    }
```
And result is something like
```
test-1: Name = TestNG-method=test-1; interrupted = false
test-1: Name = TestNG-method=test-1; interrupted = false

org.testng.internal.thread.ThreadTimeoutException: Method ThreadNameTest.test() didn't finish within the time-out 300

	at java.base@11.0.3/java.lang.Thread.sleep(Native Method)
	at app//ThreadNameTest.test(ThreadNameTest.java:10)
	at java.base@11.0.3/java.lang.Thread.run(Thread.java:834)

test-1: Name = TestNG-method=test-1; interrupted = true
test-1: Name = TestNG-method=test-1; interrupted = true
test-2: Name = TestNG-method=test-1; interrupted = false
test-1: Name = TestNG-method=test-1; interrupted = true
test-2: Name = TestNG-method=test-1; interrupted = false
test-1: Name = TestNG-method=test-1; interrupted = true

org.testng.internal.thread.ThreadTimeoutException: Method ThreadNameTest.test() didn't finish within the time-out 300

	at java.base@11.0.3/java.lang.Thread.sleep(Native Method)
	at app//ThreadNameTest.test(ThreadNameTest.java:10)
	at java.base@11.0.3/java.lang.Thread.run(Thread.java:834)

```
You can see, that first test is interrupted, but keeps running when second test starts. Both threads have same name (TestNG-method=test-1)

**Comment by juherr** [comment]
AI triage verdict: **still relevant**.

The original scenario is still structurally possible in the current code. `MethodInvocationHelper.invokeWithTimeoutWithNewExecutor()` creates a fresh executor for a timed invocation via `ThreadUtil.createExecutor(..., tm.getMethodName())`. `ThreadUtil` creates a new `TestNGThreadFactory`, and each factory owns an `AtomicInteger` initialized to `1`. Therefore overlapping timed invocations of the same method can still produce identical names such as `TestNG-method=<method>-1`.

Current timeout coverage in `test.timeout.TimeOutTest` verifies timeout status/duration behavior, but does not assert uniqueness of thread names. I found no source/test/`CHANGES.txt` reference to `#2091` or `GITHUB-2091`, and no direct open or merged PR implementing this request. PR #3451 currently touches the timeout executor-selection path for `parallel="tests"`, but it fixes #1333 and does not address thread-name uniqueness in the original non-parallel/new-executor scenario.

The historical reproducer was **not executed** during this triage; confirmation here is based on the direct current-code path above.

Next step: add a minimal regression test first. A bounded data-driven test should let the first timed invocation ignore its first interruption long enough to overlap with the next invocation, capture both worker thread names, and assert that the simultaneously alive TestNG threads have distinct names. Only after that test fails on current code should the naming/executor implementation be changed, with neighboring timeout and custom-executor behavior rechecked.
