### ISSUE TITLE
module-info is not a class because access_flag ACC_MODULE is set

### ISSUE THREAD

**Issue by tulsi26ram** [testng-team/testng#2333]
### TestNG Version
> Note: only the latest version is supported
7.1.0

### Expected behavior
Should be able to execute Testng from command lin

### Actual behavior
Getting the following exception when I run TestNG from command line

Exception in thread "main" java.lang.NoClassDefFoundError: module-info is not a class because access_flag ACC_MODULE is set
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:332)
        at org.testng.internal.ClassHelper.forName(ClassHelper.java:93)
        at org.testng.xml.XmlClass.loadClass(XmlClass.java:72)
        at org.testng.xml.XmlClass.init(XmlClass.java:67)
        at org.testng.xml.XmlClass.init(XmlClass.java:58)
        at org.testng.xml.XmlClass.<init>(XmlClass.java:34)
        at org.testng.xml.internal.XmlSuiteUtils.constructXmlClassesUsing(XmlSuiteUtils.java:75)
        at org.testng.xml.internal.XmlSuiteUtils.newXmlSuiteUsing(XmlSuiteUtils.java:48)
        at org.testng.JarFileUtils.extractSuitesFrom(JarFileUtils.java:58)
        at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:382)
        at org.testng.TestNG.initializeEverything(TestNG.java:987)
        at org.testng.TestNG.run(TestNG.java:999)
        at org.testng.TestNG.privateMain(TestNG.java:1336)
        at org.testng.TestNG.main(TestNG.java:1304)

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by tulsi26ram** [comment]
I have used the following command

java -cp mysnapshot-fat-tests.jar org.testng.TestNG -testjar mysnapshot-fat-tests.jar -xmlpathinjar MainRegression.xml

Note: MainRegression is in project root folder

**Comment by krmahadevan** [comment]
@tulsi26ram - Theres a very good chance that this could be due to incompatibilities between TestNG and JDK12 because we haven't officially certified TestNG to work fine with a JDK higher than 8. So I would suggest that you please try with JDK8 and see if that helps.

**Comment by cpowell36** [comment]
@krmahadevan do you know if this has ever been resolved? I am experiencing something similar with Java 17. Is the max version of java for testng documented somewhere? I was only able to find a min version mentioned in the testng documentation

**Comment by krmahadevan** [comment]
@cpowell36 - 7.5 ( latest release) version min jdk version is jdk8. 
7.6 ( future release) will start needing min jdk as jdk11. 

No there is no evaluation or documentation created for testng max jdk compatibility.

**Comment by krmahadevan** [comment]
If you are on 7.5 and still seeing this then it means its not resolved yet. I havent had a chance to get to this issue yet.

**Comment by bb-cn-himanshu** [comment]
@krmahadevan I am also getting same error with TestNG Version: `7.6.1`
My JDK Version is: 17, also tried with JDK 11

```
[ERROR] There was an error in the forked process
[ERROR] META-INF/versions/9/module-info is not a class because access_flag ACC_MODULE is set
[ERROR] java.lang.NoClassDefFoundError: META-INF/versions/9/module-info is not a class because access_flag ACC_MODULE is set
[ERROR] 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[ERROR] 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
[ERROR] 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
[ERROR] 	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
[ERROR] 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
[ERROR] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
[ERROR] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
[ERROR] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[ERROR] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[ERROR] 	at java.base/java.lang.Class.forName0(Native Method)
[ERROR] 	at java.base/java.lang.Class.forName(Class.java:375)
[ERROR] 	at org.testng.internal.ClassHelper.forName(ClassHelper.java:93)
[ERROR] 	at org.testng.xml.XmlClass.loadClass(XmlClass.java:71)
[ERROR] 	at org.testng.xml.XmlClass.getSupportClass(XmlClass.java:80)
[ERROR] 	at org.testng.internal.ClassInfoMap.<init>(ClassInfoMap.java:27)
[ERROR] 	at org.testng.internal.ClassInfoMap.<init>(ClassInfoMap.java:20)
[ERROR] 	at org.testng.TestRunner.initMethods(TestRunner.java:439)
[ERROR] 	at org.testng.TestRunner.init(TestRunner.java:335)
[ERROR] 	at org.testng.TestRunner.init(TestRunner.java:288)
[ERROR] 	at org.testng.TestRunner.<init>(TestRunner.java:178)
[ERROR] 	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:639)
[ERROR] 	at org.testng.SuiteRunner.init(SuiteRunner.java:225)
[ERROR] 	at org.testng.SuiteRunner.<init>(SuiteRunner.java:115)
[ERROR] 	at org.testng.TestNG.createSuiteRunner(TestNG.java:1349)
[ERROR] 	at org.testng.TestNG.createSuiteRunners(TestNG.java:1325)
[ERROR] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1167)
[ERROR] 	at org.testng.TestNG.runSuites(TestNG.java:1099)
[ERROR] 	at org.testng.TestNG.run(TestNG.java:1067)
[ERROR] 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
[ERROR] 	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
[ERROR] 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
[ERROR] 
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] META-INF/versions/9/module-info is not a class because access_flag ACC_MODULE is set
[ERROR] java.lang.NoClassDefFoundError: META-INF/versions/9/module-info is not a class because access_flag ACC_MODULE is set
[ERROR] 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[ERROR] 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
[ERROR] 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
[ERROR] 	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
[ERROR] 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
[ERROR] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
[ERROR] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
[ERROR] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[ERROR] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[ERROR] 	at java.base/java.lang.Class.forName0(Native Method)
[ERROR] 	at java.base/java.lang.Class.forName(Class.java:375)
[ERROR] 	at org.testng.internal.ClassHelper.forName(ClassHelper.java:93)
[ERROR] 	at org.testng.xml.XmlClass.loadClass(XmlClass.java:71)
[ERROR] 	at org.testng.xml.XmlClass.getSupportClass(XmlClass.java:80)
[ERROR] 	at org.testng.internal.ClassInfoMap.<init>(ClassInfoMap.java:27)
[ERROR] 	at org.testng.internal.ClassInfoMap.<init>(ClassInfoMap.java:20)
[ERROR] 	at org.testng.TestRunner.initMethods(TestRunner.java:439)
[ERROR] 	at org.testng.TestRunner.init(TestRunner.java:335)
[ERROR] 	at org.testng.TestRunner.init(TestRunner.java:288)
[ERROR] 	at org.testng.TestRunner.<init>(TestRunner.java:178)
[ERROR] 	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:639)
[ERROR] 	at org.testng.SuiteRunner.init(SuiteRunner.java:225)
[ERROR] 	at org.testng.SuiteRunner.<init>(SuiteRunner.java:115)
[ERROR] 	at org.testng.TestNG.createSuiteRunner(TestNG.java:1349)
[ERROR] 	at org.testng.TestNG.createSuiteRunners(TestNG.java:1325)
[ERROR] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1167)
[ERROR] 	at org.testng.TestNG.runSuites(TestNG.java:1099)
[ERROR] 	at org.testng.TestNG.run(TestNG.java:1067)
[ERROR] 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
[ERROR] 	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
[ERROR] 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
[ERROR] 
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:701)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:311)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:268)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1334)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1167)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:931)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR] 	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
[ERROR] 
[ERROR]
```

**Comment by krmahadevan** [comment]
@bb-cn-himanshu Can you quickly check with `7.7.0`. I remember fixing something around these lines.

**Comment by cowwoc** [comment]
Should this issue be closed?

**Comment by krmahadevan** [comment]
@cowwoc - Its not yet fixed in TestNG. We will be glad to help review/merge any PRs that you may be willing to submit for this.

**Comment by juherr** [comment]
Triage verdict: **still relevant**.

This is still present in current master. `JarFileUtils.testngXmlExistsInJar()` treats every JAR entry ending in `.class` as a Java test-class candidate; `constructClassName()` then turns entries such as `META-INF/versions/9/module-info.class` into a class name. That value is eventually loaded through `XmlClass`/`ClassHelper`, matching the reported `ACC_MODULE` failure. The current `JarFileUtilsTest` coverage does not include a multi-release JAR/module descriptor, and I found no `GITHUB-2333` regression test or merged/open PR fixing it.

The minimal regression is small: build a test JAR containing a normal TestNG class plus `module-info.class` (ideally also the multi-release `META-INF/versions/9/module-info.class` form), run it through `-testjar`/`JarFileUtils`, and assert only loadable class entries are added. The likely production fix is to exclude module descriptors (and probably `META-INF/versions/**` from naive class discovery unless multi-release semantics are intentionally supported).

**Comment by kalayciburak** [comment]
Working on this: skip module-info.class and META-INF/versions entries when discovering classes in a test jar.
