### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space - JUnitXMLReporter.generateReport(JUnitXMLReporter.java:143)

### ISSUE THREAD

**Issue by kyleshrader** [testng-team/testng#2335]
### TestNG Version
> 7.1.0

### Expected behavior
Expecting the following reports to be generated:
![image](https://user-images.githubusercontent.com/5632571/85772118-65c43900-b6d1-11ea-9003-40a3843dbf66.png)

### Actual behavior
Received the included exception during report generation and only `target/surefire-reports/junit/Surefire suite/Surefire test.html` was generated.

### Exception
```
[ERROR] Exception in provider
[ERROR] org.apache.maven.surefire.booter.SurefireExecutionException: Exception in provider
[ERROR] at org.apache.maven.plugin.surefire.InPluginVMSurefireStarter.runSuitesInProcess(InPluginVMSurefireStarter.java:91)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1166)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[ERROR] at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
[ERROR] at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
[ERROR] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
[ERROR] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
[ERROR] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] Caused by: java.lang.OutOfMemoryError: Java heap space
[ERROR] at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
[ERROR] at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:172)
[ERROR] at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:748)
[ERROR] at java.base/java.lang.StringBuilder.append(StringBuilder.java:241)
[ERROR] at org.testng.internal.Utils.escapeUnicode(Utils.java:371)
[ERROR] at org.testng.internal.Utils.writeUtf8File(Utils.java:93)
[ERROR] at org.testng.reporters.JUnitXMLReporter.generateReport(JUnitXMLReporter.java:143)
[ERROR] at org.testng.reporters.JUnitXMLReporter.onFinish(JUnitXMLReporter.java:86)
[ERROR] at org.testng.TestRunner.fireEvent(TestRunner.java:895)
[ERROR] at org.testng.TestRunner.afterRun(TestRunner.java:859)
[ERROR] at org.testng.TestRunner.run(TestRunner.java:590)
[ERROR] at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[ERROR] at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[ERROR] at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[ERROR] at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[ERROR] at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[ERROR] at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[ERROR] at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
[ERROR] at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
[ERROR] at org.testng.TestNG.runSuites(TestNG.java:1039)
[ERROR] at org.testng.TestNG.run(TestNG.java:1007)
[ERROR] at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
[ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
[ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
[ERROR] at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
[ERROR] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:206)
[ERROR] at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:161)
[ERROR] at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:84)
```

### Is the issue reproductible on runner?
- [X] Maven

### Test case sample
> None available. Running 500,000+ tests using data provider.

**Comment by krmahadevan** [comment]
@kyleshrader - Are you seeing this even after bumping up your JVM memory settings via the sure fire plugin? I think you should try running this with a higher JVM memory settings. I say this because the number of tests is huge.

@juherr @cbeust Your thoughts?

**Comment by juherr** [comment]
Similar answer as https://github.com/cbeust/testng/issues/2334#issuecomment-650049503

**Comment by juherr** [comment]
Triage verdict: **probably still relevant**.

The exact 7.1.0 OOM was not reproduced during this triage, so I am not marking it confirmed. However, the current JUnit XML reporting path still retains all relevant `ITestResult`s and builds the report in memory before writing it. That preserves the structural risk reported here for very large DataProvider runs.

A useful current reproducer should isolate `JUnitXMLReporter` with a large invocation count / DataProvider and a constrained heap, then record peak heap and the failure point. This should be addressed as a reporting-memory problem rather than as a Maven-specific behavior.
