### ISSUE TITLE
ITestResult Thread Not Used in TestListenerAdapter Extended Classes onTestSuccess/Failure/Skipped

### ISSUE THREAD

**Issue by egglestonbd** [testng-team/testng#2478]
### Summary
When configuring a setupMethod with ITestResult, annotated with @BeforeMethod, and then populating attributes to be used in correlating the failure in a test method (@Test), the ITestResult thread is not available to the listener class extending the TestListenerAdapter.

Note, this works in version 6.14.0, but fails starting 7.0.0.

### TestNG Version
7.3.0

### Expected behavior
ITestResult Thread to be populated with attributes assigned in a test method.

### Actual behavior
Only the ITestResults populated prior to the @Test method are available onTestSuccess (or onTestFailure or onTestSkipped)

### Is the issue reproducible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

### Test case sample
```
package org.mygroup;

import org.testng.ITestResult;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import static org.testng.Assert.assertFalse;

public class TestSample {

  private ThreadLocal<ITestResult> tr = new ThreadLocal<>();

  TestSample() {
  }

  @BeforeMethod(alwaysRun = true)
  public void setupMethod(ITestResult tr) {
    this.tr.set(tr);
    tr.setAttribute("field1", "value1");
    tr.setAttribute("field2", "value2");
    System.out.println("Attribute names size in Setup: " + tr.getAttributeNames().size());

  }

  @AfterClass(alwaysRun = true)
  public void tearDown() {
    tr.remove();
  }

  @Test(groups = {"acceptance"})
  public void testInvocation() {
    //These values aren't included in the Listener after v7.0.0
    tr.get().setAttribute("field3", "value3");
    tr.get().setAttribute("field4", "value4");
    System.out.println("Attribute names size in test: " + tr.getAttributeNames().size());

    assertFalse(true);
  }
}
```
The Listener that reveals only the first two fields are loaded:

```
package org.mygroup;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

import org.testng.ITestResult;
import org.testng.TestListenerAdapter;

public class Listener extends TestListenerAdapter {

  @Override
  public void onTestFailure(ITestResult tr) {
    getTestResultLogObject(tr);
  }

  @Override
  public void onTestSkipped(ITestResult tr) {
    printTestResultAttributes(tr);
  }

  @Override
  public void onTestSuccess(ITestResult tr) {
    getTestResultLogObject(tr);
  }

  void printTestResultAttributes(ITestResult tr) {
    System.out.println("Attribute names size in Listener: " + tr.getAttributeNames().size());
    System.out.println(getAttributes(tr));
  }

  private Map<String, String> getAttributes(ITestResult tr) {
    Set<String> names = tr.getAttributeNames();
    Map<String, String> attributes = new HashMap<>();
    for (String name : names) {
      Object value = tr.getAttribute(name);
      if (null == value) {
        attributes.put(name, "null");
      }
      else {
        attributes.put(name, value.toString());
      }
    }
    return attributes;
  }

}
```

**Comment by juherr** [comment]
Hi,

Could you try without the `ThreadLocal` and passing the `ITestResult` as test param? `testInvocation(ITestResult tr)`?

**Comment by egglestonbd** [comment]
@juherr ,
When passing `ITestResult` as a parameter, we get the following error.  (This is the reason we use a `ThreadLocal`).

```
[Utils] [ERROR] [Error] org.testng.TestNGException: 
Cannot inject @Test annotated Method [testInvocation] with [interface org.testng.ITestResult].
For more information on native dependency injection please refer to https://testng.org/doc/documentation-main.html#native-dependency-injection
        at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:437)
        at org.testng.internal.Parameters.createParametersForMethod(Parameters.java:351)
        at org.testng.internal.Parameters.createParameters(Parameters.java:708)
        at org.testng.internal.Parameters.handleParameters(Parameters.java:875)
        at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
        at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
        at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
        at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:789)
        at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Attribute names size in Listener: 0
{}
[TestNG] Reporter [FailedReporter passed=0 failed=0 skipped=0] failed
java.lang.NullPointerException
        at java.util.HashMap.putMapEntries(HashMap.java:501)
        at java.util.HashMap.putAll(HashMap.java:785)
        at org.testng.xml.XmlClass.setParameters(XmlClass.java:233)
        at org.testng.reporters.FailedReporter.createXmlClasses(FailedReporter.java:199)
        at org.testng.reporters.FailedReporter.createXmlTest(FailedReporter.java:150)
        at org.testng.reporters.FailedReporter.generateXmlTest(FailedReporter.java:124)
        at org.testng.reporters.FailedReporter.generateFailureSuite(FailedReporter.java:64)
        at org.testng.reporters.FailedReporter.generateReport(FailedReporter.java:49)
        at org.testng.TestNG.generateReports(TestNG.java:1099)
        at org.testng.TestNG.run(TestNG.java:1042)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
        at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.526 s <<< FAILURE! - in TestSuite
[ERROR] testInvocation(org.familysearch.paas.sps.acceptance.TestSample)  Time elapsed: 6.424 s  <<< FAILURE!
org.testng.TestNGException: 

Cannot inject @Test annotated Method [testInvocation] with [interface org.testng.ITestResult].
For more information on native dependency injection please refer to https://testng.org/doc/documentation-main.html#native-dependency-injection
```

Also updated the examples with more print statements.

**Comment by egglestonbd** [comment]
@juherr ,
We have noticed also when using `@Test ( timeOut = <some int> )`, the test is executed in a timer's subthread, breaking the ability to access the `ThreadLocal` variable.  I am wondering if going from version 6.14 to 7.0 tests are by default spun up in a different thread.  If so, is there a way to preserve the ITestResult through the new thread?

**Comment by juherr** [comment]
I'm not surprised by the exception because `ITestResult` is designed for the result.

In fact, I'm not understanding what problem you are trying to solve with `ITestResut` injected in the configuration method. Could `ITestContext` work instead?

And yes, the timeout feature is creating a new thread.

**Comment by egglestonbd** [comment]
@juherr,
We are trying to correlate test setup values with failures, such when a failure (or any test result) occurs, we can correlate the failure to the specific setup data.  The only object available to the Test Listener is the ITestResult, therefore, we are adding attributes of the setup to the ITestResult attributes, so they will be available to us when the test succeeds, fails, or is skipped, and we then can directly correlate the failure to its setup data.  

Without this correlation, we must go to the test and indirectly ascertain the setup data that caused the failure.  Yes, we can add this correlation data to the message of the asserts, but it is a much less elegant solution than to have the data available in Test Listener to format our message.  The more elegant is to handle the reporting a common class ie. in the Test Listener.

**Comment by juherr** [comment]
`TestContext` is available too: https://javadoc.jitpack.io/com/github/cbeust/testng/master/javadoc/org/testng/ITestResult.html#getTestContext--

And when you say data, I think `DataProvider` with https://javadoc.jitpack.io/com/github/cbeust/testng/master/javadoc/org/testng/ITestResult.html#getParameters--

Could you detail more your needs? I'm not sure but I wonder if you are not using an uncommon solution to a common problem.

**Comment by egglestonbd** [comment]
@juherr,
Thank you.  Yes, we can update the `ITestContext` attributes in the test, and then use `getTestContext` attribute calls.  
(Sorry I used "data" generically to mean any setup variables).

**Comment by juherr** [comment]
Can I consider the issue closed?

**Comment by egglestonbd** [comment]
Yes.  Thank you!

**Comment by krmahadevan** [comment]
@egglestonbd - Please also note that, TestNG by default would ensure that even a `beforeInvocation()` and `afterInvocation()` listener call happens on the same thread. Here's a cleaned up version of your same test code (This is using TestNG `7.3.0`)

```java
import org.testng.ITestResult;
import org.testng.Reporter;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

import static org.testng.Assert.fail;

@Listeners(MySampleListener.class)
public class TestSample {

  @BeforeMethod(alwaysRun = true)
  public void setupMethod(ITestResult tr) {
    tr.setAttribute("field1", "value1");
    tr.setAttribute("field2", "value2");
    System.out.println("Attribute names size in Setup: " + tr.getAttributeNames().size());
  }

  @Test
  public void testInvocation() {
    //This gets hold of the test result of the current test method.
    ITestResult testResult = Reporter.getCurrentTestResult();
    testResult.setAttribute("field3", "value3");
    testResult.setAttribute("field4", "value4");
    System.out.println("Attribute names size in test: " + testResult.getAttributeNames().size());
    fail("Simulating a failure");
  }
}
```

```java
import java.util.Map;
import java.util.Optional;
import java.util.stream.Collectors;
import org.testng.IInvokedMethod;
import org.testng.IInvokedMethodListener;
import org.testng.ITestResult;

public class MySampleListener implements IInvokedMethodListener {

  @Override
  public void afterInvocation(IInvokedMethod method, ITestResult testResult) {
    printTestResultAttributes(testResult);
  }

  void printTestResultAttributes(ITestResult tr) {
    String msg = String.format("[%s] method [%s] had [%d] attributes and its status was %s",
        parseMethodType(tr),
        tr.getMethod().getQualifiedName(),
        tr.getAttributeNames().size(),
        parseStatus(tr)
    );
    System.out.println(msg);
    System.out.println(getAttributes(tr));
  }

  private static String parseMethodType(ITestResult tr) {
    return (tr.getMethod().isTest() ? "test" : "configuration");
  }

  private static String parseStatus(ITestResult tr) {
    switch (tr.getStatus()) {
      case ITestResult.SUCCESS:
      case ITestResult.SUCCESS_PERCENTAGE_FAILURE:
        return "passed";
      case ITestResult.FAILURE:
        return "failed";
      case ITestResult.SKIP:
        return "skipped";
      default:
        return "unknown";
    }
  }

  private Map<String, String> getAttributes(ITestResult tr) {
    return tr.getAttributeNames()
        .stream()
        .collect(
            Collectors.toMap(
                name -> name,
                name -> Optional.ofNullable(tr.getAttribute(name))
                    .orElse("null").toString()
            )
        );
  }
}
```

And here's the output

```
Attribute names size in Setup: 2
[configuration] method [com.rationaleemotions.github.issue2478.TestSample.setupMethod] had [0] attributes and its status was passed
{}
Attribute names size in test: 4
[test] method [com.rationaleemotions.github.issue2478.TestSample.testInvocation] had [4] attributes and its status was failed
{field1=value1, field3=value3, field2=value2, field4=value4}

java.lang.AssertionError: Simulating a failure

	at org.testng.Assert.fail(Assert.java:99)
	at com.rationaleemotions.github.issue2478.TestSample.testInvocation(TestSample.java:28)
```

Closing this issue as requested.
