### ISSUE TITLE
TextReporter should not be allowed to be disabled

### ISSUE THREAD

**Issue by 736773174** [testng-team/testng#2654]
### TestNG Version
> Note: only the latest version is supported
Latest Version

### Scenario

When I run TestNG I don't want it to generate extra xml files, so I setUseDefaultListeners(false).
but I still expect it to log passes/failures/stacktraces to console, and this is not the case.

### Expected behavior

There should be a minimum experience TestNG supports that cannot be disabled, and I think TextReporter is one of those.
See this line, TextReporter should not be switch off-able.

https://github.com/cbeust/testng/blob/b703fdc81a3a6f1ed3d0dee92c035ad3903178b6/testng-core/src/main/java/org/testng/SuiteRunner.java#L643

Alternative is to have a version of TextReporter that's addable to the main TestNG Object and not every TestSuiteRunner.
 
Possible implementation:
- make VerboseReporter verbose level controllable and similar to TextReporter

### Actual behavior
If default listeners are disabled, then TextReporter is disabled.

### Is the issue reproducible on runner?

- [X] Shell
- [X] Maven
- [X] Gradle
- [X] Ant
- [X] Eclipse
- [X] IntelliJ
- [X] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

When default listener disabled the following will not be logged, nothing will be logged

```
PASSED: checkInsidePackageTest
FAILED: checkClassTest
java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.fail(Assert.java:106)
	at com.mytest.testclasses.DummyClass.checkClassTest(DummyClass.java:13)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by 736773174** [comment]
Hey maybe I'm misunderstanding how TextReporter is used.
From what I'm seeing, a new TextReporter is initialized per suite, so if I have multiple suites I'd have to initialize multiple TextReporter?

> via a service loader mechanism, so that you dont need to add to your suite a reference of it.

I'm not super sure what this means, do you have an example?

> Are you trying to disable default listeners and still at-least have 1 listener work for you all the time?

I guess I'm saying there should be a minimum experience, that's not optional. Users could disable a bunch of default listeners, but they should still be able to debug their tests. 
No TextReporter means no stack trace or pass/failure indication on the test cases

**Comment by krmahadevan** [comment]
@736773174 

> I'm not super sure what this means, do you have an example? Sounds like a quick fix I can do to get the same experience as opposed to the VerboseReporter

Refer to https://testng.org/doc/documentation-main.html#listeners-service-loader for more information.

> I guess I'm saying there should be a minimum experience, that's not optional. Users could disable a bunch of default listeners, but they should still be able to debug their tests.

We will look at what constitutes a minimal reporting mechanism which cannot be removed. The problem with making this decision is that the minimal reporting means different things to different people. For some folks it may be the emailable report that is a minimal reporting and for others it may be the text reporter.

Maybe we can bifurcate the html and text reporters as two different categories. 

But like I said, you can still disable everything and hard wire the reporting listener of your choice as a mandatory reporting listener for your project using the service loading mechanism which should work seamlessly.

**Comment by juherr** [comment]
@krmahadevan maybe we can use the listener node and allow "-" before the classname in order to unselect classes.

**Comment by 736773174** [comment]
> Refer to https://testng.org/doc/documentation-main.html#listeners-service-loader for more information

Hey the way I'm executing tests is through referencing the TestNG object, like below
```
final TestNG testNG = new TestNG();
testNG.setXmlSuites(Collections.singletonList(xmlSuite));
testNG.run();
```
From the Service loader seems like there maybe a way I can add the TextReporter from the top level TestNG object? or is my guess wrong :(

> minimal reporting means different things to different people

Yeah you are right. I think the only thing I'm not happy with is struggling to enable the TextReporter, and this maybe on me.
 
However the TextReporter is controlled by Verbose Lvl and can be disabled by the verbose level. So I think it's unnecessary to also have it controlled by the defaultListener flag?

**Comment by juherr** [comment]
To be honest, I don't see any good reason why we should not allow to disable TextReporter.

If you only want it, you just have to add it as a listener of your suite and it should do the job.

**Comment by krmahadevan** [comment]
@736773174 - We seem to be going around in circles. If you wire in a listener via the service loader approach, you dont need to explicitly pin it back to the suite. TestNG will take care of automatically handling it for you.  So please add it via a service loader like how its mentioned in the docs and after that TestNG will automatically take care of ensuring that those listeners are wired in to the respective suite files without you having to do anything extra.

**Comment by juherr** [comment]
```java
testNG.addListener(new TextReporter("name", 1));
```

**Comment by juherr** [comment]
Triage verdict: **working as designed**.

Current `SuiteRunner` still adds `TextReporter` inside the `useDefaultListeners` block together with the other built-in reporters, so `setUseDefaultListeners(false)` intentionally disables it. The code even retains the historical comment asking whether users rely on that behavior. The original discussion also converged on keeping `TextReporter` optional: the reporter agreed, and the programmatic use case was answered with `testNG.addListener(new TextReporter("name", 1))`; ServiceLoader is another supported option.

#2646 later streamlined internal logging, but it did not change this reporter lifecycle. I found no #2654 / `GITHUB-2654` implementation, current regression test changing this contract, or open/merged PR that makes `TextReporter` mandatory.

I did **not** execute the historical scenario. The current behavior matches the intended `useDefaultListeners` contract, and making `TextReporter` non-disableable would be a behavior change rather than a bug fix.

Closing as intentional behavior; users who disable all defaults can explicitly add `TextReporter` when they still want console test-result output.
