### ISSUE TITLE
NPE is triggered when working with ITestObjectFactory

### ISSUE THREAD

**Issue by krmahadevan** [testng-team/testng#2676]
### TestNG Version
> Note: only the latest version is supported

`7.5-SNAPSHOT`

### Expected behaviour

No NPE should be seen.

### Actual behaviour

Noticing an NPE.

```
java.lang.NullPointerException
	at org.testng.SuiteRunner.init(SuiteRunner.java:160)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:114)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1323)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1299)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1144)
	at org.testng.TestNG.runSuites(TestNG.java:1076)
	at org.testng.TestNG.run(TestNG.java:1044)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
```

### Is the issue reproducible on runner?

- [ ] Shell
- [X] Maven
- [X] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

```java
import org.testng.annotations.Test;

public class TestClass {

  @Test
  public void testMethod() {
    System.err.println("Test Method invoked");
  }
}
```

```java
import java.lang.reflect.Constructor;
import org.testng.ITestObjectFactory;

public class MyFactory implements ITestObjectFactory {

  @Override
  public Object newInstance(Constructor constructor, Object... params) {
    System.err.println("Factory getting called.");
    try {
      return constructor.newInstance(params);
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }
}
```

```java
import java.util.List;
import org.testng.IAlterSuiteListener;
import org.testng.xml.XmlSuite;

public class LocalSuiteAlteringListener implements IAlterSuiteListener {

  @Override
  public void alter(List<XmlSuite> suites) {
    suites.forEach(each -> each.setObjectFactoryClass(MyFactory.class));
  }
}
```

`META-INF/services/org.testng.ITestNGListener` contents

```
com.rationaleemotions.objects.LocalSuiteAlteringListener
```

Exception being noticed:

```
java.lang.NullPointerException
	at org.testng.SuiteRunner.init(SuiteRunner.java:160)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:114)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1323)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1299)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1144)
	at org.testng.TestNG.runSuites(TestNG.java:1076)
	at org.testng.TestNG.run(TestNG.java:1044)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
```

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by dalexandrov** [comment]
Just wondering, when to expect this release? As our integration is depending on this functionality.
Thank you)

**Comment by juherr** [comment]
@dalexandrov Soon
