### ISSUE TITLE
TestNG 7.8.0

### ISSUE THREAD

**Issue by DenizDalkilic10** [testng-team/testng#2969]
### Expected behavior
The test method runs properly with a data provider and group name provided.

### Actual behavior
The test method throws a java.nio.file.AccessDeniedException when the test is executed. It works as expected when a dataprovider or a group is provided individually to the method. 

```
java.lang.RuntimeException: java.nio.file.AccessDeniedException: 

	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:57)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:157)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:803)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:728)
	at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
	at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:911)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.nio.file.AccessDeniedException: 
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:234)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:379)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:431)
	at java.base/java.nio.file.Files.readAllBytes(Files.java:3263)
	at java.base/java.nio.file.Files.readString(Files.java:3341)
	at util.PropertyManager.readJsonData(PropertyManager.java:54)
	at tests.CollectionsTests.GetCollectionTest.collectionsByCultureDP(GetCollectionTest.java:103)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:53)
	... 12 more
```

### Test case sample
```java
@Test(groups = {"Smoke"}, dataProvider = "CollectionsByCultureDP")
 
public void getCollectionsByCulture(String culture, int expectedStatusCode) {// Todo}
```

**Comment by juherr** [comment]
The issue comes from

```
at util.PropertyManager.readJsonData(PropertyManager.java:54)
	at tests.CollectionsTests.GetCollectionTest.collectionsByCultureDP(GetCollectionTest
```

which is not part of TestNG.

**Comment by krmahadevan** [comment]
There is nothing in the stacktrace that indicates this to be a TestNG problem. Please help share a reproducible project that can be used to recreate this issue.

To help debug this, I would suggest that you please create a `public static void main()` method that just invokes `PropertyManager.readJsonData()` with a valid json on your windows machine and see if that works.
