### ISSUE TITLE
ConcurrentModificationException when injecting values

### ISSUE THREAD

**Issue by lucianoRM** [testng-team/testng#3048]
### TestNG Version
7.7.1

### Expected behavior
No exception

### Actual behavior
We got a random exception when executing our test suite. I actually don't know if this is a rare case, but maybe it's worth looking at.

```
java.util.ConcurrentModificationException: null
    at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
    at org.testng.collections.MultiMap.get(MultiMap.java:36)
    at org.testng.internal.objects.GuiceHelper.getGuiceModules(GuiceHelper.java:125)
    at org.testng.internal.objects.GuiceHelper.getModules(GuiceHelper.java:189)
    at org.testng.internal.objects.GuiceHelper.getInjector(GuiceHelper.java:70)
    at org.testng.internal.objects.GuiceBasedObjectDispenser.dispense(GuiceBasedObjectDispenser.java:47)
    at org.testng.internal.BaseTestMethod.computeRetryAnalyzerInstanceToUse(BaseTestMethod.java:816)
    at org.testng.internal.BaseTestMethod.getRetryAnalyzerConsideringMethodParameters(BaseTestMethod.java:787)
    at org.testng.internal.BaseTestMethod.getRetryAnalyzer(BaseTestMethod.java:651)
    at org.testng.internal.invokers.TestInvoker.shouldRetryTestMethod(TestInvoker.java:562)
    at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:732)
    at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
    at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
    at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
    at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
    at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
    at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:840)
```

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by krmahadevan** [comment]
@lucianoRM - Please upgrade to `7.7.1` and let me know if you still see the problem. If yes, then it would be good if you could please help share a sample that can be used to reproduce the issue.
