### ISSUE TITLE
ClassCastException when use shouldUseGlobalThreadPool(true) property

### ISSUE THREAD

**Issue by X-NoNAME** [testng-team/testng#3179]
### TestNG Version
> 7.10.2

### Expected behavior
no exceptions

### Actual behavior
there is exception:
```java
java.lang.ClassCastException: class org.testng.internal.thread.graph.TestNGFutureTask cannot be cast to class org.testng.internal.thread.Async$AsyncTask (org.testng.internal.thread.graph.TestNGFutureTask and org.testng.internal.thread.Async$AsyncTask are in unnamed module of loader 'app')
	at org.testng.internal.thread.Async$AsyncTask.compareTo(Async.java:22)
	at java.base/java.util.concurrent.PriorityBlockingQueue.siftUpComparable(PriorityBlockingQueue.java:353)
	at java.base/java.util.concurrent.PriorityBlockingQueue.offer(PriorityBlockingQueue.java:475)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357)
	at org.testng.internal.thread.Async.run(Async.java:18)
	at org.testng.internal.invokers.MethodRunner.runInParallel(MethodRunner.java:143)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:982)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### Is the issue reproducible on runner?
- Gradle

### Test case sample
```java
public class ClassCastExceptionExample implements IAlterSuiteListener {
  @Override
  public void alter(List<XmlSuite> suites) {
    suites.get(0).shouldUseGlobalThreadPool(true);
    suites.get(0).setThreadCount(3);
    suites.get(0).setParallel(XmlSuite.ParallelMode.METHODS);
  }

  @DataProvider(parallel = true)
  public Object[] dp() {return new Object[]{1};}

  @Test(dataProvider = "dp") public void test1(int dp) {}
  @Test(dataProvider = "dp") public void test3(int dp) {}
  @Test public void test2() {}
  @Test public void test4() {}
}
```
```
//gradle
tasks.test {
    useTestNG() {
        testNameIncludePatterns = ["ClassCastExceptionExample.*"]
        listeners.add('ClassCastExceptionExample')
    }
}
```

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by krmahadevan** [comment]
The root cause of the problem is how TestNG determines if it should use a `LinkedBlockingQueue` or a `PriorityBlockingQueue`

* `PriorityBlockingQueue` is to be used when TestNG detects that there are tests that have priorities defined.
* `LinkedBlockingQueue1 is to be used for all other cases.

The flaw lies with how we determine which of the queues to use. 

Currently the logic considers both priority as well if any `org.testng.IMethodInterceptor` have been wired in. See [here](https://github.com/testng-team/testng/blob/f0e73919bdec2a786983cf0fa250f22b33368249/testng-core/src/main/java/org/testng/TestRunner.java#L665-L668)

When 

```
//gradle
tasks.test {
    useTestNG() {
        testNameIncludePatterns = ["ClassCastExceptionExample.*"]
        listeners.add('ClassCastExceptionExample')
    }
}
```

is used, Gradle sees that there is filtering enabled via `testNameIncludePatterns = ["ClassCastExceptionExample.*"]` it ends up adding an implementation of IMethodInterceptor 

See [here](https://github.com/gradle/gradle/blob/8cfa39227cbac5f78fa412df662258625e5cae56/platforms/jvm/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/testng/TestNGTestClassProcessor.java#L143-L145) and 

[here](https://github.com/gradle/gradle/blob/8cfa39227cbac5f78fa412df662258625e5cae56/platforms/jvm/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/testng/TestNGTestClassProcessor.java#L235C26-L255)

This should be fixed in a day or two (I have the fix ready)

**Comment by krmahadevan** [comment]
@Zlaman - Sure. We will get this done shortly. Need to straighten up some stuff with the release process due to the recent hanges in sonatype repository.

**Comment by erohaniupgrade** [comment]
is 7.12.0 going to be released ?

**Comment by misahthieu** [comment]
I'm facing with this issue. please release fix version asap!
