### ISSUE TITLE
testNG not creating HTML report

### ISSUE THREAD

**Issue by rab2215** [testng-team/testng#562]
I'm receiving the following error once my selenium/testNG test suite has completed execution, and as a result the HTML report is not being generated.

[TestNG] Reporter org.testng.reporters.jq.Main@6218d77b failed
java.lang.NullPointerException
    at org.testng.reporters.FileStringBuffer.append(FileStringBuffer.java:50)
    at org.testng.reporters.FileStringBuffer.append(FileStringBuffer.java:28)
    at org.testng.reporters.XMLUtils.xml(XMLUtils.java:27)
    at org.testng.reporters.XMLUtils.xmlRequired(XMLUtils.java:63)
    at org.testng.reporters.XMLStringBuffer.addRequired(XMLStringBuffer.java:201)
    at org.testng.reporters.XMLStringBuffer.addRequired(XMLStringBuffer.java:204)
    at org.testng.reporters.jq.ReporterPanel.getContent(ReporterPanel.java:40)
    at org.testng.reporters.jq.BaseMultiSuitePanel.generate(BaseMultiSuitePanel.java:24)
    at org.testng.reporters.jq.Main.generateReport(Main.java:63)
    at org.testng.TestNG.generateReports(TestNG.java:1115)
    at org.testng.TestNG.run(TestNG.java:1074)
    at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:91)
    at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
    at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
    at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

It's a somewhat intermittent issue, as I can run 2-3 tests without a problem. Executing any more than that causes the error.  This is preventing me from being able to review the results of running multiple tests locally before committing the new tests.  This test suite runs in a Jenkins job and publishes the results using the TestNG plugin.  I am seeing the error there as well, but the plugin is able to display the results of the tests.  

I'm using TestNG version 6.8.8 and executing the tests with maven-surefire-plugin 2.16, but I have tried using 2.17 and encountered the same error.

**Comment by qiuxiafei** [comment]
have this issue been fixed in version `6.8.13`? 
I have the same problem after updating to `6.8.13`

**Comment by VladRassokhin** [comment]
@qiuxiafei attach stacktrace, please.

**Comment by VladRassokhin** [comment]
@qiuxiafei ok, there another problem, seems 'line.separator' system property is missing. Will create pull request to fix that.

**Comment by qiuxiafei** [comment]
It happens on my Mac and also Linux.
Mac envirenment is:
- OS 10.10.1 (14B25)
- java version "1.7.0_60"

Linux envirenment is:
- Red Hat Enterprise Linux Server release 5.7 (Tikanga)
- java version "1.7.0_51"

**Comment by qiuxiafei** [comment]
I thinks there's something wrong with jar loading. The line number of FileStringBuffer.java does not match the source file downloaded from maven repo.

**Comment by VladRassokhin** [comment]
@qiuxiafei try cleaning maven cache, etc. ensure you have latest version of library.

**Comment by qiuxiafei** [comment]
I figure out this problem finally. There was a case which clear the system properties like:

```java
System.setProperties(new Properties());
// ...
```

this clean system properties and affect TestNG's action. Not only `line.seperator`, but also other properties like temp path were cleared. So this is my fault.

But adding a default value for each of these properties may be an improvent of  robustness.

**Comment by krmahadevan** [comment]
Closing this issue (due to staleness). Please comment if the issue persists in TestNG `7.8.0` (latest released version)
