### ISSUE TITLE
Can not find the dependent test method

### ISSUE THREAD

**Issue by ghost** [testng-team/testng#609]
Environment: 
1) Eclipse: Eclipse IDE for Java Developers
Version: Luna Service Release 1 (4.4.1)
Build id: 20140925-1800
2)TestNG plugin: For Eclipse 3.4 and above, enter http://beust.com/eclipse. Notes: I used this one to install testNG plugin.
3)JDK1.7.0_72

Repro steps: 
1. Create below class:

``` java
package cn.testng.my;

import org.testng.annotations.Test;


public class TestCase1 {
  @Test
  public void f() {
      System.out.println("Hello testNGa.");
     // Assert.assertEquals(3, 3);
      String str = "NIHAO";
      assert "abc".equals(str) : "expected: abc, actual: " + str;
  }

  @Test(dependsOnMethods={"f"})
  public void b()
  {
      System.out.println("Hello testNGb. This test cases depends on test method f. HelloNGa");
  }
}
```

Notes: if just run test method of this class, then b test method will be skipped. Cause test method f will fail and b test method depends on method f.
1. Data Provider class:

``` java
package cn.testng.my;

import org.testng.annotations.DataProvider;

public class DataProviderMethod {
    @DataProvider(name="d")
    public static Object[][] dataProvider4(){
        return new Object[][]{
                {30}
        };
    }

}
```

3.Test Data Provider

``` java
package cn.testng.my;

import org.testng.Assert;
import org.testng.annotations.Optional;
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

@Test(dependsOnMethods={"f"})
public class TestDataProvider{
    public String name; 

    @Parameters(value="name")
    public TestDataProvider(@Optional("Linda") String name) {
        this.name = name;
    }

    @Test(dataProvider="d", dataProviderClass=DataProviderMethod.class) 
    public void test3(int ages){
        System.out.println("My name is " + name);
        int actual = 30;
        Assert.assertEquals(actual, ages, "Data mismatch.");        
    }

}
```
1. From the above class, we can see that the whole class depends on test method f. But when run this class. The exception will be thrown.

```
org.testng.TestNGException: 
cn.testng.my.TestDataProvider.test3() depends on nonexistent method f
    at org.testng.internal.MethodHelper.findDependedUponMethods(MethodHelper.java:114)
    at org.testng.internal.MethodHelper.topologicalSort(MethodHelper.java:240)
    at org.testng.internal.MethodHelper.sortMethods(MethodHelper.java:317)
    at org.testng.internal.MethodHelper.collectAndOrderMethods(MethodHelper.java:59)
    at org.testng.TestRunner.initMethods(TestRunner.java:481)
    at org.testng.TestRunner.init(TestRunner.java:235)
    at org.testng.TestRunner.init(TestRunner.java:205)
    at org.testng.TestRunner.<init>(TestRunner.java:160)
    at org.testng.remote.RemoteTestNG$1.newTestRunner(RemoteTestNG.java:141)
    at org.testng.remote.RemoteTestNG$DelegatingTestRunnerFactory.newTestRunner(RemoteTestNG.java:271)
    at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:561)
    at org.testng.SuiteRunner.init(SuiteRunner.java:157)
    at org.testng.SuiteRunner.<init>(SuiteRunner.java:111)
    at org.testng.TestNG.createSuiteRunner(TestNG.java:1299)
    at org.testng.TestNG.createSuiteRunners(TestNG.java:1286)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
    at org.testng.TestNG.run(TestNG.java:1057)
    at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
```

I don't know why.

**Comment by davebirch** [comment]
Pretty sure that dependsOnMethods only works within the scope of the
current class. For something like this where you want your dependencies to
work cross-class you're better off assigning groups to your methods and
using dependsOnGroups which I can confirm does work cross class.

**Comment by cbeust** [comment]
Correct. You can't depend on a method of another class since TestNG can't
know what instance it should use.

Use groups for this: put the method you want to depend on in a group and
have the other method depend on that group.

-- 
Cédric

**Comment by CynthiaWuSky** [comment]
Okay. Thanks.

**Comment by juherr** [comment]
TODO: ignore + warn when `dependsOnMethods` is used on a class

**Comment by krmahadevan** [comment]
Here's what I have observed using TestNG `7.8.0`

```java
package com.rationaleemotions.github.issue609;

import org.testng.annotations.Test;

public class FirstClassExample {

  @Test
  public void firstMethod() {}
}
```

```java
package com.rationaleemotions.github.issue609;

import org.testng.annotations.Test;

public class SecondClassExample {

  @Test(dependsOnMethods = "com.rationaleemotions.github.issue609.FirstClassExample.firstMethod")
  public void secondMethod() {}
}
```

When using an IDE such as Intellij and running `SecondClassExample` the plugin automatically runs the dependencies as well (As seen in below screenshot)

<img width="937" alt="image" src="https://github.com/testng-team/testng/assets/909773/92706156-571f-4040-81ff-5702f4c4eb21">

But when we create a suite file such as below, 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="609_suite">
  <test thread-count="5" name="609_test" verbose="2">
    <classes>
      <class name="com.rationaleemotions.github.issue609.SecondClassExample"/>
    </classes>
  </test>
</suite>

```

executing the above suite file, triggers an error that looks like below

```shell
org.testng.TestNGException: 
com.rationaleemotions.github.issue609.SecondClassExample.secondMethod() is depending on method public void com.rationaleemotions.github.issue609.FirstClassExample.firstMethod(), which is not annotated with @Test or not included.
	at org.testng.internal.MethodHelper.findDependedUponMethods(MethodHelper.java:203)
	at org.testng.internal.MethodHelper.topologicalSort(MethodHelper.java:349)

// deleted the rest of the stacktrace for brievity
```
