### ISSUE TITLE
NPE in DependencyMap.getMethodDependingOn() with filtering IMethodInterceptor

### ISSUE THREAD

**Issue by lbergelson** [testng-team/testng#690]
I have a CI system that runs one build on multiple nodes, and provides each node with environment variables that say how many nodes there are total, and what number node you're currently running on.  I want to evenly split my tests across the nodes by distributing them according to some value mod the number of total nodes.  

I wrote a custom IMethodInterceptor to implement this, but it usually crashes with a NPE

```
  public class ParallelSplittingListener implements org.testng.IMethodInterceptor {
        private final int totalNodes;
        private final int nodeNumber;

        public ParallelSplittingListener(){
            String totalString = System.getenv("CIRCLE_NODE_TOTAL");
            String indexString = System.getenv("CIRCLE_NODE_INDEX");
            if ( totalString != null && indexString != null) {
                this.totalNodes = Integer.valueOf(totalString);
                this.nodeNumber = Integer.valueOf(indexString);
            } else {
                this.totalNodes = -1;
                this.nodeNumber = 1;
            }
        }

        @Override
        public List<IMethodInstance> intercept(List<IMethodInstance> methods, ITestContext context) {
            if (totalNodes > 1 && nodeNumber > -1 ) {
                List<IMethodInstance> result = new ArrayList<>();
                for (IMethodInstance m : methods) {
                    int shard = m.getMethod().getMethodName().hashCode() % totalNodes;
                    if (shard == nodeNumber) {
                        result.add(m);
                    }
                }
                return result;
            } else {
                return methods;
            }
        }
    }
```

I'm invoking my tests through gradle, so the stack trace includes gradle stuff, but the cause seems to be `DependencyMap.getMethodDependingOn`  

```
org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not complete execution for Gradle Test Executor 1.
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy2.stop(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:116)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at org.testng.DependencyMap.getMethodDependingOn(DependencyMap.java:58)
    at org.testng.TestRunner.createDynamicGraph(TestRunner.java:1062)
    at org.testng.TestRunner.privateRun(TestRunner.java:734)
    at org.testng.TestRunner.run(TestRunner.java:617)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
    at org.testng.SuiteRunner.run(SuiteRunner.java:254)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
    at org.testng.TestNG.run(TestNG.java:1057)
    at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:136)
    at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:80)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:59)
    ... 22 more
```

The documentation on  `IMethodInterceptor` says 

> Only methods that have no dependents and that don't depend on any other test methods will
> be passed in parameter.  Implementers of this interface need to return a list of {@link IMethodInstance}
> that represents the list of test methods they want run.  TestNG will run these methods in the
> same order found in the returned value.

That makes me think that I should be able to arbitrarily filter this list without causing any problems, but it seems like it does cause problems.  I did see #215, but I'm not sure it addressed the issue I'm having, since I'm not editing any dependencies at all, I just want to filter tests out.

**Comment by cbeust** [comment]
Your understanding matches mine, since you are only altering the list of free methods, this should have zero impacts on dependency code. Not quite sure what's going on.

**Comment by lbergelson** [comment]
I'm invoking TestNG through Gradle.  I'm not sure if how that would change things, but it's probably relevant.

Here's the `test` block of my gradle file.  I think the only potentially important lines are the listener and maybe the excludeGroups.  Removing the exclude groups doesn't fix the error though.

````
test {
        // enable TestNG support (default is JUnit)
        useTestNG{
            excludeGroups 'cloud', 'bucket'
            listeners << "org.broadinstitute.hellbender.ParallelSplittingListener"
        }

    // set heap size for the test JVM(s)
    minHeapSize = "1G"
    maxHeapSize = "2G"

    String CI = "$System.env.CI"
    if (CI == "true") {
        int count = 0
        // listen to events in the test execution lifecycle
        testLogging {
            events "skipped", "failed"
            exceptionFormat = "full"
        }

        beforeTest { descriptor ->
            count++
            if( count % 10000 == 0) {
                logger.lifecycle("Finished "+ Integer.toString(count++) + " tests")
            }
        }
    } else {
        // show standard out and standard error of the test JVM(s) on the console
        testLogging.showStandardStreams = true
        beforeTest { descriptor ->
            logger.lifecycle("Running Test: " + descriptor)
        }

        // listen to standard out and standard error of the test JVM(s)
        onOutput { descriptor, event ->
            logger.lifecycle("Test: " + descriptor + " produced standard out/err: " + event.message )
        }
    }
}
````

I'm using gradle 2.4, testng 6.9.4, and running on java 8.

**Comment by krmahadevan** [comment]
I am not able to reproduce this problem using TestNG `6.14.3` (the latest released version). Please comment if this is still a problem and also help share a reproducible test.
