### ISSUE TITLE
Order of execution when @Factory at constructor level

### ISSUE THREAD

**Issue by sandy999s** [testng-team/testng#892]
I am facing some issues as the order of execution is not correct when there is @Factory at constructor level and there are some tests are present..

I have provided the DataProvider(lazy fashion) as my data gets generated at RUNTIME at my original setup

I have simplified for illustrations and source code is attached in 

https://groups.google.com/forum/#!topic/testng-dev/_m04AT9Dy1Q
## ExpectedResult
# b4Class for sun_company3

TEST 1 :Executing forsun_company3 IP : sun_company3 ENTRY 1

TEST 1 :Executing forsun_company3 IP : sun_company3 ENTRY 2

Test 2: sun_company3 IP : sun_company3 ENTRY 1

Test 2: sun_company3 IP : sun_company3 ENTRY 2
# Closing sun_company3
# b4Class for sun_company4

TEST 1 :Executing forsun_company4 IP : sun_company4 ENTRY 1

TEST 1 :Executing forsun_company4 IP : sun_company4 ENTRY 2

Test 2: sun_company4 IP : sun_company4 ENTRY 1

Test 2: sun_company4 IP : sun_company4 ENTRY 2
# Closing sun_company4

But the Actual Result i am facing is  :-
# b4Class for sun_company3

TEST 1 :Executing forsun_company3 IP : sun_company3 ENTRY 1

TEST 1 :Executing forsun_company3 IP : sun_company3 ENTRY 2
# b4Class for sun_company4

TEST 1 :Executing forsun_company4 IP : sun_company4 ENTRY 1

TEST 1 :Executing forsun_company4 IP : sun_company4 ENTRY 2

Test 2: sun_company3 IP : sun_company4 ENTRY 1

Test 2: sun_company3 IP : sun_company4 ENTRY 2
# Closing sun_company3

Test 2: sun_company4 IP : sun_company4 ENTRY 1

Test 2: sun_company4 IP : sun_company4 ENTRY 2
# Closing sun_company4

**Comment by juherr** [comment]
Did you try the `group-by-instances="true"` as I proposed you?

**Comment by sandy999s** [comment]
If i have put group-by-instances="true", then i am getting the following exception :

sun_company3,sun_company4
THE COMPANY SETTING AS Default test name
DATAACCESORS :FROM DATAPROVIDER : getACCCOUNTS INITIALIZED:sun_company3,sun_company4
THE COMPANY SETTING AS sun_company3
THE COMPANY SETTING AS sun_company4
[TestNG] Running:
  D:\Projects\SMSConnect\Automation\Billing\TESTS\src\testng.xml

org.testng.TestNGException: 
No free nodes found in:[DynamicGraph 
  Ready:[data.testik()[pri:0, instance:data@1b4de03], checkParsing.Test1(java.lang.String)[pri:0, instance:checkParsing@813486], checkParsing.Test1(java.lang.String)[pri:0, instance:checkParsing@9f624a], checkParsing.Test2(java.lang.String)[pri:0, instance:checkParsing@813486], checkParsing.Test2(java.lang.String)[pri:0, instance:checkParsing@9f624a]]
  Running:[]
  Finished:[]
  Edges:
     checkParsing.Test2(java.lang.String)[pri:0, instance:checkParsing@813486]
        data.testik()[pri:0, instance:data@1b4de03]
     checkParsing.Test1(java.lang.String)[pri:0, instance:checkParsing@9f624a]
        checkParsing.Test2(java.lang.String)[pri:0, instance:checkParsing@9f624a]
     checkParsing.Test1(java.lang.String)[pri:0, instance:checkParsing@813486]
        checkParsing.Test2(java.lang.String)[pri:0, instance:checkParsing@813486]
        data.testik()[pri:0, instance:data@1b4de03]
     data.testik()[pri:0, instance:data@1b4de03]
        checkParsing.Test1(java.lang.String)[pri:0, instance:checkParsing@813486]
        checkParsing.Test1(java.lang.String)[pri:0, instance:checkParsing@9f624a]
        checkParsing.Test2(java.lang.String)[pri:0, instance:checkParsing@813486]
        checkParsing.Test2(java.lang.String)[pri:0, instance:checkParsing@9f624a]
        checkParsing.Test1(java.lang.String)[pri:0, instance:checkParsing@9f624a]
        checkParsing.Test2(java.lang.String)[pri:0, instance:checkParsing@9f624a]
]
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)

**Comment by sandy999s** [comment]
Hi juherr , 

Did you got time to look into this issue...

Should i need to provide any extra data

Thanks,
Sandeep

**Comment by juherr** [comment]
> Did you got time to look into this issue...

Not yet

**Comment by juherr** [comment]
Well, I created a test case from your sample: https://github.com/juherr/testng/commit/9214b2663d99cac8a31796e4f65871e526c1b946

The output is:
With XML:

```
DPClassGitHub892(sun_company1,sun2_company2) Thread:main
FactoryDataProviderGitHub892Sample(Default test name) Thread:main
DPClassGitHub892#getAccounts:[sun_company1, sun2_company2] Thread:main
FactoryDataProviderGitHub892Sample(sun_company1) Thread:main
FactoryDataProviderGitHub892Sample(sun2_company2) Thread:main
DPClassGitHub892:tests Thread:main
FactoryDataProviderGitHub892Sample#beforeClass with:sun_company1 Thread:main
FactoryDataProviderGitHub892Sample#test1: sun_company1 IP: sun_company1 ENTRY 1 Thread:main
FactoryDataProviderGitHub892Sample#test1: sun_company1 IP: sun_company1 ENTRY 2 Thread:main
FactoryDataProviderGitHub892Sample#beforeClass with:sun2_company2 Thread:main
FactoryDataProviderGitHub892Sample#test1: sun2_company2 IP: sun2_company2 ENTRY 1 Thread:main
FactoryDataProviderGitHub892Sample#test1: sun2_company2 IP: sun2_company2 ENTRY 2 Thread:main
FactoryDataProviderGitHub892Sample#test2: sun_company1 IP: sun2_company2 ENTRY 1 Thread:main
FactoryDataProviderGitHub892Sample#test2: sun_company1 IP: sun2_company2 ENTRY 2 Thread:main
FactoryDataProviderGitHub892Sample#afterClass sun_company1 Thread:main
FactoryDataProviderGitHub892Sample#test2: sun2_company2 IP: sun2_company2 ENTRY 1 Thread:main
FactoryDataProviderGitHub892Sample#test2: sun2_company2 IP: sun2_company2 ENTRY 2 Thread:main
FactoryDataProviderGitHub892Sample#afterClass sun2_company2 Thread:main
```

With CLI:

```
DPClassGitHub892(sun_company1,sun2_company2) Thread:main
FactoryDataProviderGitHub892Sample(Default test name) Thread:main
DPClassGitHub892#getAccounts:[sun_company1, sun2_company2] Thread:main
FactoryDataProviderGitHub892Sample(sun_company1) Thread:main
FactoryDataProviderGitHub892Sample(sun2_company2) Thread:main
DPClassGitHub892:tests Thread:main
FactoryDataProviderGitHub892Sample#beforeClass with:sun2_company2 Thread:main
FactoryDataProviderGitHub892Sample#test1: sun2_company2 IP: sun2_company2 ENTRY 1 Thread:main
FactoryDataProviderGitHub892Sample#test1: sun2_company2 IP: sun2_company2 ENTRY 2 Thread:main
FactoryDataProviderGitHub892Sample#test2: sun2_company2 IP: sun2_company2 ENTRY 1 Thread:main
FactoryDataProviderGitHub892Sample#test2: sun2_company2 IP: sun2_company2 ENTRY 2 Thread:main
FactoryDataProviderGitHub892Sample#afterClass sun2_company2 Thread:main
FactoryDataProviderGitHub892Sample#beforeClass with:sun_company1 Thread:main
FactoryDataProviderGitHub892Sample#test1: sun_company1 IP: sun_company1 ENTRY 1 Thread:main
FactoryDataProviderGitHub892Sample#test1: sun_company1 IP: sun_company1 ENTRY 2 Thread:main
FactoryDataProviderGitHub892Sample#test2: sun_company1 IP: sun_company1 ENTRY 1 Thread:main
FactoryDataProviderGitHub892Sample#test2: sun_company1 IP: sun_company1 ENTRY 2 Thread:main
FactoryDataProviderGitHub892Sample#afterClass sun_company1 Thread:main
```

If I understand well, you'd like to see the CLI output instead of the XML one?
As they are supposed to be identical, I agree to say there is an issue somewhere :)

But notice that your usage of TestNG (using static data provider initialized from the constructor) is not really strong and may fail later.

**Comment by juherr** [comment]
Closing this as a historical issue that is no longer actionable against the current TestNG codebase.

The original reproducer was added only in a maintainer fork and was never incorporated into the main regression suite, so the exact scenario has not been reproduced on current `master`.

Since then, the relevant factory/instance handling has changed substantially, including #1467, #326, and #3089. Current tests also cover factory-instance grouping and `group-by-instances` with method dependencies, and I could not find a newer report reproducing the specific cross-instance `DataProvider` leakage described here.

If this still occurs with a current TestNG release, please open a new issue with a minimal up-to-date reproducer.
